//------------------------------------------------------------------------------
// <auto-generated>
//     Ce code a été généré par un outil.
//     Version du runtime :4.0.30319.42000
//
//     Les modifications apportées à ce fichier peuvent provoquer un comportement incorrect et seront perdues si
//     le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Neos.IdentityServer.Console.Resources {
    using System;
    
    
    /// <summary>
    ///   Une classe de ressource fortement typée destinée, entre autres, à la consultation des chaînes localisées.
    /// </summary>
    // Cette classe a été générée automatiquement par la classe StronglyTypedResourceBuilder
    // à l'aide d'un outil, tel que ResGen ou Visual Studio.
    // Pour ajouter ou supprimer un membre, modifiez votre fichier .ResX, puis réexécutez ResGen
    // avec l'option /str ou régénérez votre projet VS.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "15.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class errors_strings {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal errors_strings() {
        }
        
        /// <summary>
        ///   Retourne l'instance ResourceManager mise en cache utilisée par cette classe.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Neos.IdentityServer.Console.Resources.errors_strings", typeof(errors_strings).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Remplace la propriété CurrentUICulture du thread actuel pour toutes
        ///   les recherches de ressources à l'aide de cette classe de ressource fortement typée.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à This machine is not an ADFS Server 2012R2 / 2016 !.
        /// </summary>
        internal static string ErrorADFSPlatformNotSupported {
            get {
                return ResourceManager.GetString("ErrorADFSPlatformNotSupported", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à ADFS Service not available !.
        /// </summary>
        internal static string ErrorADFSServerNotRunning {
            get {
                return ResourceManager.GetString("ErrorADFSServerNotRunning", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Error loading MFA Configuration ! \r {0}.
        /// </summary>
        internal static string ErrorLoadingMFAConfiguration {
            get {
                return ResourceManager.GetString("ErrorLoadingMFAConfiguration", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à MFA is already initialized ! you must run &quot;UnRegister-MFASytem&quot; PowerShell Cmdlet if you want to reinitialize ALL the MFA configuration.
        /// </summary>
        internal static string ErrorMFAFarmAlreadyInitialized {
            get {
                return ResourceManager.GetString("ErrorMFAFarmAlreadyInitialized", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à MFA not initialized ! you must run &quot;Register-MFASystem&quot; PowerShell  Cmdlet.
        /// </summary>
        internal static string ErrorMFAFarmNotInitialized {
            get {
                return ResourceManager.GetString("ErrorMFAFarmNotInitialized", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Acces denied for current user ! must be an ADFS admin.
        /// </summary>
        internal static string ErrorMFAUnAuthorized {
            get {
                return ResourceManager.GetString("ErrorMFAUnAuthorized", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Sensitive mail sent to user {0}.
        /// </summary>
        internal static string InfoSendingMailToUser {
            get {
                return ResourceManager.GetString("InfoSendingMailToUser", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à {0} emails sent !.
        /// </summary>
        internal static string InfosSendingMails {
            get {
                return ResourceManager.GetString("InfosSendingMails", resourceCulture);
            }
        }
    }
}
