//------------------------------------------------------------------------------
// <auto-generated>
//     Ce code a été généré par un outil.
//     Version du runtime :4.0.30319.42000
//
//     Les modifications apportées à ce fichier peuvent provoquer un comportement incorrect et seront perdues si
//     le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Neos.IdentityServer.Console.Resources {
    using System;
    
    
    /// <summary>
    ///   Une classe de ressource fortement typée destinée, entre autres, à la consultation des chaînes localisées.
    /// </summary>
    // Cette classe a été générée automatiquement par la classe StronglyTypedResourceBuilder
    // à l'aide d'un outil, tel que ResGen ou Visual Studio.
    // Pour ajouter ou supprimer un membre, modifiez votre fichier .ResX, puis réexécutez ResGen
    // avec l'option /str ou régénérez votre projet VS.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "15.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Neos_IdentityServer_Console_Nodes {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Neos_IdentityServer_Console_Nodes() {
        }
        
        /// <summary>
        ///   Retourne l'instance ResourceManager mise en cache utilisée par cette classe.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Neos.IdentityServer.Console.Resources.Neos.IdentityServer.Console.Nodes", typeof(Neos_IdentityServer_Console_Nodes).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Remplace la propriété CurrentUICulture du thread actuel pour toutes
        ///   les recherches de ressources à l'aide de cette classe de ressource fortement typée.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Active Directory configuration.
        /// </summary>
        public static string ADDSSCOPENODEDESC {
            get {
                return ResourceManager.GetString("ADDSSCOPENODEDESC", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Azure configuration.
        /// </summary>
        public static string AZURESCOPENODEDESC {
            get {
                return ResourceManager.GetString("AZURESCOPENODEDESC", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Cancel.
        /// </summary>
        public static string GENERALSCOPECANCEL {
            get {
                return ResourceManager.GetString("GENERALSCOPECANCEL", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Cancel updates.
        /// </summary>
        public static string GENERALSCOPECANCELDESC {
            get {
                return ResourceManager.GetString("GENERALSCOPECANCELDESC", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Global parameters.
        /// </summary>
        public static string GENERALSCOPENODEDESC {
            get {
                return ResourceManager.GetString("GENERALSCOPENODEDESC", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Save.
        /// </summary>
        public static string GENERALSCOPESAVE {
            get {
                return ResourceManager.GetString("GENERALSCOPESAVE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Save updates.
        /// </summary>
        public static string GENERALSCOPESAVEDESC {
            get {
                return ResourceManager.GetString("GENERALSCOPESAVEDESC", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à MFA Providers .
        /// </summary>
        public static string MFASCOPENODEDESC {
            get {
                return ResourceManager.GetString("MFASCOPENODEDESC", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Change language.
        /// </summary>
        public static string ROOTCHANGELANGUAGE {
            get {
                return ResourceManager.GetString("ROOTCHANGELANGUAGE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Change the culture of the user interface.
        /// </summary>
        public static string ROOTCHANGELANGUAGEDESC {
            get {
                return ResourceManager.GetString("ROOTCHANGELANGUAGEDESC", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Spain.
        /// </summary>
        public static string ROOTLANGUAGEES {
            get {
                return ResourceManager.GetString("ROOTLANGUAGEES", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Change the user interface culture in Spanish (3082).
        /// </summary>
        public static string ROOTLANGUAGEESDESC {
            get {
                return ResourceManager.GetString("ROOTLANGUAGEESDESC", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à French.
        /// </summary>
        public static string ROOTLANGUAGEFR {
            get {
                return ResourceManager.GetString("ROOTLANGUAGEFR", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Changing the culture of the user interface in French (1036).
        /// </summary>
        public static string ROOTLANGUAGEFRDESC {
            get {
                return ResourceManager.GetString("ROOTLANGUAGEFRDESC", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à United States.
        /// </summary>
        public static string ROOTLANGUAGEUS {
            get {
                return ResourceManager.GetString("ROOTLANGUAGEUS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Change the culture of the user interface in English (1033).
        /// </summary>
        public static string ROOTLANGUAGEUSDESC {
            get {
                return ResourceManager.GetString("ROOTLANGUAGEUSDESC", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à MFA.
        /// </summary>
        public static string ROOTSCOPENODEDESC {
            get {
                return ResourceManager.GetString("ROOTSCOPENODEDESC", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Security configuration.
        /// </summary>
        public static string SECURITYSCOPENODEDESC {
            get {
                return ResourceManager.GetString("SECURITYSCOPENODEDESC", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Services status.
        /// </summary>
        public static string SERVICESCOPENODEDESC {
            get {
                return ResourceManager.GetString("SERVICESCOPENODEDESC", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Phone configuration.
        /// </summary>
        public static string SMSSCOPENODEDESC {
            get {
                return ResourceManager.GetString("SMSSCOPENODEDESC", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à SMTP configuration.
        /// </summary>
        public static string SMTPSCOPENODEDESC {
            get {
                return ResourceManager.GetString("SMTPSCOPENODEDESC", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à SQLServer configuration.
        /// </summary>
        public static string SQLSCOPENODEDESC {
            get {
                return ResourceManager.GetString("SQLSCOPENODEDESC", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à TOTP configuration.
        /// </summary>
        public static string TOTPSCOPENODEDESC {
            get {
                return ResourceManager.GetString("TOTPSCOPENODEDESC", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Add a user.
        /// </summary>
        public static string USERSCOPEADDUSER {
            get {
                return ResourceManager.GetString("USERSCOPEADDUSER", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Add a user to the MFA authentication system.
        /// </summary>
        public static string USERSCOPEADDUSERDESC {
            get {
                return ResourceManager.GetString("USERSCOPEADDUSERDESC", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Clear user filter.
        /// </summary>
        public static string USERSCOPEFILTERCLEAR {
            get {
                return ResourceManager.GetString("USERSCOPEFILTERCLEAR", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Clear the filter from the user list.
        /// </summary>
        public static string USERSCOPEFILTERCLEARDESC {
            get {
                return ResourceManager.GetString("USERSCOPEFILTERCLEARDESC", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Filter users.
        /// </summary>
        public static string USERSCOPEFILTERUSERS {
            get {
                return ResourceManager.GetString("USERSCOPEFILTERUSERS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Filter the list of users.
        /// </summary>
        public static string USERSCOPEFILTERUSERSDESC {
            get {
                return ResourceManager.GetString("USERSCOPEFILTERUSERSDESC", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Import.
        /// </summary>
        public static string USERSCOPEIMPORT {
            get {
                return ResourceManager.GetString("USERSCOPEIMPORT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Import Active Directory Users.
        /// </summary>
        public static string USERSCOPEIMPORTADDS {
            get {
                return ResourceManager.GetString("USERSCOPEIMPORTADDS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Import users from ADDS.
        /// </summary>
        public static string USERSCOPEIMPORTADDSDESC {
            get {
                return ResourceManager.GetString("USERSCOPEIMPORTADDSDESC", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Import CSV users.
        /// </summary>
        public static string USERSCOPEIMPORTCSV {
            get {
                return ResourceManager.GetString("USERSCOPEIMPORTCSV", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Import users from a CSV file.
        /// </summary>
        public static string USERSCOPEIMPORTCSVDESC {
            get {
                return ResourceManager.GetString("USERSCOPEIMPORTCSVDESC", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Procedures for importing users.
        /// </summary>
        public static string USERSCOPEIMPORTDESC {
            get {
                return ResourceManager.GetString("USERSCOPEIMPORTDESC", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Import XML users.
        /// </summary>
        public static string USERSCOPEIMPORTXML {
            get {
                return ResourceManager.GetString("USERSCOPEIMPORTXML", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Import users from a XML file.
        /// </summary>
        public static string USERSCOPEIMPORTXMLDESC {
            get {
                return ResourceManager.GetString("USERSCOPEIMPORTXMLDESC", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Properties: New User.
        /// </summary>
        public static string USERSPROPERTYADD {
            get {
                return ResourceManager.GetString("USERSPROPERTYADD", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Number of users imported : {0}  Errors : {1}.
        /// </summary>
        public static string USERSSCOPEIMPORTCSVCOUNT {
            get {
                return ResourceManager.GetString("USERSSCOPEIMPORTCSVCOUNT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Invalid csv file !.
        /// </summary>
        public static string USERSSCOPEIMPORTCSVINVALID {
            get {
                return ResourceManager.GetString("USERSSCOPEIMPORTCSVINVALID", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à CSV import results.
        /// </summary>
        public static string USERSSCOPEIMPORTCSVRESTITLE {
            get {
                return ResourceManager.GetString("USERSSCOPEIMPORTCSVRESTITLE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Import users in MFA with a csv file.
        /// </summary>
        public static string USERSSCOPEIMPORTCSVTITLE {
            get {
                return ResourceManager.GetString("USERSSCOPEIMPORTCSVTITLE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Number of users imported : {0}  Errors : {1}.
        /// </summary>
        public static string USERSSCOPEIMPORTXMLCOUNT {
            get {
                return ResourceManager.GetString("USERSSCOPEIMPORTXMLCOUNT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à XML import results.
        /// </summary>
        public static string USERSSCOPEIMPORTXMLRESTITLE {
            get {
                return ResourceManager.GetString("USERSSCOPEIMPORTXMLRESTITLE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Import users in MFA with a xml file.
        /// </summary>
        public static string USERSSCOPEIMPORTXMLTITLE {
            get {
                return ResourceManager.GetString("USERSSCOPEIMPORTXMLTITLE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Users management.
        /// </summary>
        public static string USERSSCOPENODEDESC {
            get {
                return ResourceManager.GetString("USERSSCOPENODEDESC", resourceCulture);
            }
        }
    }
}
