//------------------------------------------------------------------------------
// <auto-generated>
//     Ce code a été généré par un outil.
//     Version du runtime :4.0.30319.42000
//
//     Les modifications apportées à ce fichier peuvent provoquer un comportement incorrect et seront perdues si
//     le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Neos.IdentityServer.MultiFactor.Cmdlets.Ressources {
    using System;
    
    
    /// <summary>
    ///   Une classe de ressource fortement typée destinée, entre autres, à la consultation des chaînes localisées.
    /// </summary>
    // Cette classe a été générée automatiquement par la classe StronglyTypedResourceBuilder
    // à l'aide d'un outil, tel que ResGen ou Visual Studio.
    // Pour ajouter ou supprimer un membre, modifiez votre fichier .ResX, puis réexécutez ResGen
    // avec l'option /str ou régénérez votre projet VS.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class infos_strings {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal infos_strings() {
        }
        
        /// <summary>
        ///   Retourne l'instance ResourceManager mise en cache utilisée par cette classe.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Neos.IdentityServer.MultiFactor.Cmdlets.Ressources.infos_strings", typeof(infos_strings).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Remplace la propriété CurrentUICulture du thread actuel pour toutes
        ///   les recherches de ressources à l'aide de cette classe de ressource fortement typée.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à All RSA keys will be invalidated ! Continue (Y/N).
        /// </summary>
        internal static string InfoAllKeyWillbeReset {
            get {
                return ResourceManager.GetString("InfoAllKeyWillbeReset", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à All Farm Services Restarted !.
        /// </summary>
        internal static string InfosAllServicesRestarted {
            get {
                return ResourceManager.GetString("InfosAllServicesRestarted", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à MFA Configuration updated !.
        /// </summary>
        internal static string InfosConfigUpdated {
            get {
                return ResourceManager.GetString("InfosConfigUpdated", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Database &quot;{0}&quot; created !.
        /// </summary>
        internal static string InfosDatabaseCreated {
            get {
                return ResourceManager.GetString("InfosDatabaseCreated", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Records count : {0}.
        /// </summary>
        internal static string InfosRecordsCount {
            get {
                return ResourceManager.GetString("InfosRecordsCount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à MFA certificate correctly updated !.
        /// </summary>
        internal static string InfosRSACertificateChanged {
            get {
                return ResourceManager.GetString("InfosRSACertificateChanged", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Services on server &quot;{0}&quot; Restarted !.
        /// </summary>
        internal static string InfosServerServicesRestarted {
            get {
                return ResourceManager.GetString("InfosServerServicesRestarted", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à MFA is already initialized ! you must run &quot;UnRegister-MFASytem&quot; PowerShell Cmdlet if you want to reinitialize ALL the MFA configuration.
        /// </summary>
        internal static string InfosSystemAlreadyInitialized {
            get {
                return ResourceManager.GetString("InfosSystemAlreadyInitialized", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à MFA System correctly registered ! .
        /// </summary>
        internal static string InfosSystemRegistered {
            get {
                return ResourceManager.GetString("InfosSystemRegistered", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à MFA System correctly unconfigured !.
        /// </summary>
        internal static string InfosSystemUnRegistered {
            get {
                return ResourceManager.GetString("InfosSystemUnRegistered", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à User &quot;{0}&quot; added !.
        /// </summary>
        internal static string InfosUserAdded {
            get {
                return ResourceManager.GetString("InfosUserAdded", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à User &quot;{0}&quot; deleted !.
        /// </summary>
        internal static string InfosUserDeleted {
            get {
                return ResourceManager.GetString("InfosUserDeleted", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à User &quot;{0}&quot; has a new Enryption key !.
        /// </summary>
        internal static string InfosUserHasNewKey {
            get {
                return ResourceManager.GetString("InfosUserHasNewKey", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à User &quot;{0}&quot; updated !.
        /// </summary>
        internal static string InfosUserUpdated {
            get {
                return ResourceManager.GetString("InfosUserUpdated", resourceCulture);
            }
        }
    }
}
