//------------------------------------------------------------------------------
// <auto-generated>
//     Ce code a été généré par un outil.
//     Version du runtime :4.0.30319.42000
//
//     Les modifications apportées à ce fichier peuvent provoquer un comportement incorrect et seront perdues si
//     le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Neos.IdentityServer.Console.Resources {
    using System;
    
    
    /// <summary>
    ///   Une classe de ressource fortement typée destinée, entre autres, à la consultation des chaînes localisées.
    /// </summary>
    // Cette classe a été générée automatiquement par la classe StronglyTypedResourceBuilder
    // à l'aide d'un outil, tel que ResGen ou Visual Studio.
    // Pour ajouter ou supprimer un membre, modifiez votre fichier .ResX, puis réexécutez ResGen
    // avec l'option /str ou régénérez votre projet VS.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Neos_IdentityServer_Console_UserPropertyPages {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Neos_IdentityServer_Console_UserPropertyPages() {
        }
        
        /// <summary>
        ///   Retourne l'instance ResourceManager mise en cache utilisée par cette classe.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Neos.IdentityServer.Console.Resources.Neos.IdentityServer.Console.UserPropertyPag" +
                            "es", typeof(Neos_IdentityServer_Console_UserPropertyPages).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Remplace la propriété CurrentUICulture du thread actuel pour toutes
        ///   les recherches de ressources à l'aide de cette classe de ressource fortement typée.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Common properties.
        /// </summary>
        internal static string PPAGECOMMONTITILE {
            get {
                return ResourceManager.GetString("PPAGECOMMONTITILE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à General.
        /// </summary>
        internal static string PPAGEGENERALTITLE {
            get {
                return ResourceManager.GetString("PPAGEGENERALTITLE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Invalid secondary email address !.
        /// </summary>
        internal static string PPAGEINVALIDMAIL {
            get {
                return ResourceManager.GetString("PPAGEINVALIDMAIL", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à A valid phone number is required to receive the codes via SMS !.
        /// </summary>
        internal static string PPAGEINVALIDPHONE {
            get {
                return ResourceManager.GetString("PPAGEINVALIDPHONE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Key.
        /// </summary>
        internal static string PPAGEKEYSTITLE {
            get {
                return ResourceManager.GetString("PPAGEKEYSTITLE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à A valid digital key is required to generate TOTP codes to validate your identity !.
        /// </summary>
        internal static string PPAGEVALIDKEY {
            get {
                return ResourceManager.GetString("PPAGEVALIDKEY", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à A secondary e-mail address is required to receive e-mail codes ! \rDo you want to continue ?.
        /// </summary>
        internal static string PPAGEVALIDMAIL {
            get {
                return ResourceManager.GetString("PPAGEVALIDMAIL", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à A phone number is required to receive the codes via SMS ! \r\rDo you want to continue ?.
        /// </summary>
        internal static string PPAGEVALIDPHONE {
            get {
                return ResourceManager.GetString("PPAGEVALIDPHONE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à the name of the user can not be empty !.
        /// </summary>
        internal static string PPAGEVALIDUSER {
            get {
                return ResourceManager.GetString("PPAGEVALIDUSER", resourceCulture);
            }
        }
    }
}
