//------------------------------------------------------------------------------
// <auto-generated>
//     Ce code a été généré par un outil.
//     Version du runtime :4.0.30319.42000
//
//     Les modifications apportées à ce fichier peuvent provoquer un comportement incorrect et seront perdues si
//     le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Neos.IdentityServer.MultiFactor.Samples.Resources {
    using System;
    
    
    /// <summary>
    ///   Une classe de ressource fortement typée destinée, entre autres, à la consultation des chaînes localisées.
    /// </summary>
    // Cette classe a été générée automatiquement par la classe StronglyTypedResourceBuilder
    // à l'aide d'un outil, tel que ResGen ou Visual Studio.
    // Pour ajouter ou supprimer un membre, modifiez votre fichier .ResX, puis réexécutez ResGen
    // avec l'option /str ou régénérez votre projet VS.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "15.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class CSHtml {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal CSHtml() {
        }
        
        /// <summary>
        ///   Retourne l'instance ResourceManager mise en cache utilisée par cette classe.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Neos.IdentityServer.MultiFactor.Samples.Resources.CSHtml", typeof(CSHtml).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Remplace la propriété CurrentUICulture du thread actuel pour toutes
        ///   les recherches de ressources à l'aide de cette classe de ressource fortement typée.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Single use access code.
        /// </summary>
        internal static string OTPUICFGLabel {
            get {
                return ResourceManager.GetString("OTPUICFGLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Use my authentication application.
        /// </summary>
        internal static string OTPUIChoiceLabel {
            get {
                return ResourceManager.GetString("OTPUIChoiceLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Use my authentication application.
        /// </summary>
        internal static string OTPUIConfigLabel {
            get {
                return ResourceManager.GetString("OTPUIConfigLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Register an authenticator application.
        /// </summary>
        internal static string OTPUIEnrollTaskLabel {
            get {
                return ResourceManager.GetString("OTPUIEnrollTaskLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Account verified&lt;br&gt;&lt;br&gt;Now you can use your app to authenticate.
        /// </summary>
        internal static string OTPUIEnrollValidatedLabel {
            get {
                return ResourceManager.GetString("OTPUIEnrollValidatedLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Use your authentication application.
        /// </summary>
        internal static string OTPUIListChoiceLabel {
            get {
                return ResourceManager.GetString("OTPUIListChoiceLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Authentication application.
        /// </summary>
        internal static string OTPUIListOptionLabel {
            get {
                return ResourceManager.GetString("OTPUIListOptionLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Enter the verification code displayed in the authenticator app on your mobile device..
        /// </summary>
        internal static string OTPUIMessage {
            get {
                return ResourceManager.GetString("OTPUIMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Enter Code.
        /// </summary>
        internal static string OTPUIOTPLabel {
            get {
                return ResourceManager.GetString("OTPUIOTPLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Scan the QR Code with a TOTP application like Microsoft Authenticator, Google Authenticator for registering your account.
        /// </summary>
        internal static string OTPUIWIZComment {
            get {
                return ResourceManager.GetString("OTPUIWIZComment", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Enroll Authenticator App.
        /// </summary>
        internal static string OTPUIWIZLabel {
            get {
                return ResourceManager.GetString("OTPUIWIZLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Enroll my authentication application.
        /// </summary>
        internal static string OTPWIZEnroll {
            get {
                return ResourceManager.GetString("OTPWIZEnroll", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à TOTP Multi-Factor Provider (430).
        /// </summary>
        internal static string PROVIDEROTPDESCRIPTION {
            get {
                return ResourceManager.GetString("PROVIDEROTPDESCRIPTION", resourceCulture);
            }
        }
    }
}
