//------------------------------------------------------------------------------
// <auto-generated>
//     Ce code a été généré par un outil.
//     Version du runtime :4.0.30319.42000
//
//     Les modifications apportées à ce fichier peuvent provoquer un comportement incorrect et seront perdues si
//     le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Neos.IdentityServer.MultiFactor.Resources {
    using System;
    
    
    /// <summary>
    ///   Une classe de ressource fortement typée destinée, entre autres, à la consultation des chaînes localisées.
    /// </summary>
    // Cette classe a été générée automatiquement par la classe StronglyTypedResourceBuilder
    // à l'aide d'un outil, tel que ResGen ou Visual Studio.
    // Pour ajouter ou supprimer un membre, modifiez votre fichier .ResX, puis réexécutez ResGen
    // avec l'option /str ou régénérez votre projet VS.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class html_strings {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal html_strings() {
        }
        
        /// <summary>
        ///   Retourne l'instance ResourceManager mise en cache utilisée par cette classe.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Neos.IdentityServer.MultiFactor.Resources.html_strings", typeof(html_strings).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Remplace la propriété CurrentUICulture du thread actuel pour toutes
        ///   les recherches de ressources à l'aide de cette classe de ressource fortement typée.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Check your email account.
        /// </summary>
        internal static string HtlmUIMUseEmail {
            get {
                return ResourceManager.GetString("HtlmUIMUseEmail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Change my configuration options.
        /// </summary>
        internal static string HtmlChangeConfiguration {
            get {
                return ResourceManager.GetString("HtmlChangeConfiguration", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Change my password.
        /// </summary>
        internal static string HtmlChangePassword {
            get {
                return ResourceManager.GetString("HtmlChangePassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Email To.
        /// </summary>
        internal static string HtmlCHOOSEOptionEmailWarning {
            get {
                return ResourceManager.GetString("HtmlCHOOSEOptionEmailWarning", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à I have no such information.
        /// </summary>
        internal static string HtmlCHOOSEOptionNone {
            get {
                return ResourceManager.GetString("HtmlCHOOSEOptionNone", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Remember my selection.
        /// </summary>
        internal static string HtmlCHOOSEOptionRemember {
            get {
                return ResourceManager.GetString("HtmlCHOOSEOptionRemember", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Send Code.
        /// </summary>
        internal static string HtmlCHOOSEOptionSendCode {
            get {
                return ResourceManager.GetString("HtmlCHOOSEOptionSendCode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Enroll my biometric device.
        /// </summary>
        internal static string HtmlEnrollBiometric {
            get {
                return ResourceManager.GetString("HtmlEnrollBiometric", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Enroll my biometric device.
        /// </summary>
        internal static string HtmlEnrollBiometrics {
            get {
                return ResourceManager.GetString("HtmlEnrollBiometrics", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Enroll my personal email address.
        /// </summary>
        internal static string HtmlEnrollEmail {
            get {
                return ResourceManager.GetString("HtmlEnrollEmail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Enroll my authentication application .
        /// </summary>
        internal static string HtmlEnrollOTP {
            get {
                return ResourceManager.GetString("HtmlEnrollOTP", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Enroll my phone.
        /// </summary>
        internal static string HtmlEnrollPhone {
            get {
                return ResourceManager.GetString("HtmlEnrollPhone", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Set my PIN code.
        /// </summary>
        internal static string HtmlEnrollPinCode {
            get {
                return ResourceManager.GetString("HtmlEnrollPinCode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à wrong Identification, please restart your session.
        /// </summary>
        internal static string HtmlErrorRestartSession {
            get {
                return ResourceManager.GetString("HtmlErrorRestartSession", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Send inscription request.
        /// </summary>
        internal static string HtmlINSRequest {
            get {
                return ResourceManager.GetString("HtmlINSRequest", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Sending your inscription request via email to administrators.
        /// </summary>
        internal static string HtmlINSWaitRequest {
            get {
                return ResourceManager.GetString("HtmlINSWaitRequest", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à The verification code is invalid !
        ///You can try the operation again by selecting &quot;Previous&quot;. It will be necessary to re-register your account.
        ///If you cancel, you will not be able to use single-use code validation (the most secure).
        /// </summary>
        internal static string HtmlLabelVERIFYOTPError {
            get {
                return ResourceManager.GetString("HtmlLabelVERIFYOTPError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Finish.
        /// </summary>
        internal static string HtmlLabelVERIFYOTPOK {
            get {
                return ResourceManager.GetString("HtmlLabelVERIFYOTPOK", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Previous.
        /// </summary>
        internal static string HtmlLabelVERIFYOTPPRIOR {
            get {
                return ResourceManager.GetString("HtmlLabelVERIFYOTPPRIOR", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Your account is validated!
        ///You will be able to use single-use code validation in the future..
        /// </summary>
        internal static string HtmlLabelVERIFYOTPSuccess {
            get {
                return ResourceManager.GetString("HtmlLabelVERIFYOTPSuccess", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à You must have an authentication application such as Microsoft Authenticator, Google Authenticator installed on your device before you can continue and register your account.
        /// </summary>
        internal static string HtmlLabelWREGOTP {
            get {
                return ResourceManager.GetString("HtmlLabelWREGOTP", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à By continuing, your current key will be invalidated and reset.
        /// </summary>
        internal static string HtmlLabelWREGOTPWarning {
            get {
                return ResourceManager.GetString("HtmlLabelWREGOTPWarning", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à You must enter an email address to confirm your identiy. This email must be reachable without needing enterprise verification (personal email address).
        /// </summary>
        internal static string HtmlLabelWREmail {
            get {
                return ResourceManager.GetString("HtmlLabelWREmail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à You must enter your phone number in order to confirm your identity. This phone must be reachable..
        /// </summary>
        internal static string HtmlLabelWRPhone {
            get {
                return ResourceManager.GetString("HtmlLabelWRPhone", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à You must enter a secret code (4 digits) in order to validate your identity. Be sure not to use the codes of your bank card or telephone as well as details concerning your date of birth..
        /// </summary>
        internal static string HtmlLabelWRPinCode {
            get {
                return ResourceManager.GetString("HtmlLabelWRPinCode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Scan the QR Code with a TOTP application like Microsoft Authenticator, Google Authenticator for registering your account.
        /// </summary>
        internal static string HtmlLabelWRQRCode {
            get {
                return ResourceManager.GetString("HtmlLabelWRQRCode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Verification.
        /// </summary>
        internal static string HtmlLabelWVERIFYOTP {
            get {
                return ResourceManager.GetString("HtmlLabelWVERIFYOTP", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Cancel.
        /// </summary>
        internal static string HtmlPWDCancel {
            get {
                return ResourceManager.GetString("HtmlPWDCancel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Current password.
        /// </summary>
        internal static string HtmlPWDLabelActual {
            get {
                return ResourceManager.GetString("HtmlPWDLabelActual", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à New password.
        /// </summary>
        internal static string HtmlPWDLabelNew {
            get {
                return ResourceManager.GetString("HtmlPWDLabelNew", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Password confirmation.
        /// </summary>
        internal static string HtmlPWDLabelNewConfirmation {
            get {
                return ResourceManager.GetString("HtmlPWDLabelNewConfirmation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Save.
        /// </summary>
        internal static string HtmlPWDSave {
            get {
                return ResourceManager.GetString("HtmlPWDSave", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Default access method.
        /// </summary>
        internal static string HtmlREGAccessMethod {
            get {
                return ResourceManager.GetString("HtmlREGAccessMethod", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Configuration options.
        /// </summary>
        internal static string HtmlREGAccessPageMethods {
            get {
                return ResourceManager.GetString("HtmlREGAccessPageMethods", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Secret Key.
        /// </summary>
        internal static string HtmlREGLabelAppKey {
            get {
                return ResourceManager.GetString("HtmlREGLabelAppKey", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Personal email address.
        /// </summary>
        internal static string HtmlREGLabelMail {
            get {
                return ResourceManager.GetString("HtmlREGLabelMail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Cellphone number.
        /// </summary>
        internal static string HtmlREGLabelPhoneNumber {
            get {
                return ResourceManager.GetString("HtmlREGLabelPhoneNumber", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Let me choose the best option.
        /// </summary>
        internal static string HtmlREGOptionChooseBest {
            get {
                return ResourceManager.GetString("HtmlREGOptionChooseBest", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Send an email to your personal address.
        /// </summary>
        internal static string HtmlREGOptionEmail {
            get {
                return ResourceManager.GetString("HtmlREGOptionEmail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Send a notification to your cellphone.
        /// </summary>
        internal static string HtmlREGOptionPhone {
            get {
                return ResourceManager.GetString("HtmlREGOptionPhone", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Use a TOTP application.
        /// </summary>
        internal static string HtmlREGOptionTOTP {
            get {
                return ResourceManager.GetString("HtmlREGOptionTOTP", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Reinitialize your key.
        /// </summary>
        internal static string HtmlREGResetQR {
            get {
                return ResourceManager.GetString("HtmlREGResetQR", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Send by email.
        /// </summary>
        internal static string HtmlREGSendQR {
            get {
                return ResourceManager.GetString("HtmlREGSendQR", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Show me the QR Code.
        /// </summary>
        internal static string HtmlREGShowQR {
            get {
                return ResourceManager.GetString("HtmlREGShowQR", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Your secret key has changed!.
        /// </summary>
        internal static string HtmlSecretKeyChanged {
            get {
                return ResourceManager.GetString("HtmlSecretKeyChanged", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Access my options after authentication.
        /// </summary>
        internal static string HtmlUIMAccessOptions {
            get {
                return ResourceManager.GetString("HtmlUIMAccessOptions", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Code verification.
        /// </summary>
        internal static string HtmlUIMCheck {
            get {
                return ResourceManager.GetString("HtmlUIMCheck", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Sign In.
        /// </summary>
        internal static string HtmlUIMConnexion {
            get {
                return ResourceManager.GetString("HtmlUIMConnexion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Disable Multi-Factor authentication.
        /// </summary>
        internal static string HtmlUIMDisableMFA {
            get {
                return ResourceManager.GetString("HtmlUIMDisableMFA", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Inscription request.
        /// </summary>
        internal static string HtmlUIMGotoInscription {
            get {
                return ResourceManager.GetString("HtmlUIMGotoInscription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Change my options.
        /// </summary>
        internal static string HtmlUIMGoToRegistration {
            get {
                return ResourceManager.GetString("HtmlUIMGoToRegistration", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Use default configuration.
        /// </summary>
        internal static string HtmlUIMLabelDefault {
            get {
                return ResourceManager.GetString("HtmlUIMLabelDefault", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à I do not have the code.
        /// </summary>
        internal static string HtmlUIMNoCode {
            get {
                return ResourceManager.GetString("HtmlUIMNoCode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Ok.
        /// </summary>
        internal static string HtmlUIMOk {
            get {
                return ResourceManager.GetString("HtmlUIMOk", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Register a new email address.
        /// </summary>
        internal static string HtmlUIMRecordNewEmail {
            get {
                return ResourceManager.GetString("HtmlUIMRecordNewEmail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Get a new key.
        /// </summary>
        internal static string HtmlUIMRecordNewKey {
            get {
                return ResourceManager.GetString("HtmlUIMRecordNewKey", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Use your authenticator application.
        /// </summary>
        internal static string HtmlUIMUseApp {
            get {
                return ResourceManager.GetString("HtmlUIMUseApp", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Check for SMS on your phone.
        /// </summary>
        internal static string HtmlUIMUsePhone {
            get {
                return ResourceManager.GetString("HtmlUIMUsePhone", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Phone verification.
        /// </summary>
        internal static string HtmlUIVerifyPhone {
            get {
                return ResourceManager.GetString("HtmlUIVerifyPhone", resourceCulture);
            }
        }
    }
}
