//------------------------------------------------------------------------------
// <auto-generated>
//     Ce code a été généré par un outil.
//     Version du runtime :4.0.30319.42000
//
//     Les modifications apportées à ce fichier peuvent provoquer un comportement incorrect et seront perdues si
//     le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Neos.IdentityServer.MultiFactor.Resources {
    using System;
    
    
    /// <summary>
    ///   Une classe de ressource fortement typée destinée, entre autres, à la consultation des chaînes localisées.
    /// </summary>
    // Cette classe a été générée automatiquement par la classe StronglyTypedResourceBuilder
    // à l'aide d'un outil, tel que ResGen ou Visual Studio.
    // Pour ajouter ou supprimer un membre, modifiez votre fichier .ResX, puis réexécutez ResGen
    // avec l'option /str ou régénérez votre projet VS.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class html_strings {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal html_strings() {
        }
        
        /// <summary>
        ///   Retourne l'instance ResourceManager mise en cache utilisée par cette classe.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Neos.IdentityServer.MultiFactor.Resources.html_strings", typeof(html_strings).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Remplace la propriété CurrentUICulture du thread actuel pour toutes
        ///   les recherches de ressources à l'aide de cette classe de ressource fortement typée.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Check your email account.
        /// </summary>
        internal static string HtlmUIMUseEmail {
            get {
                return ResourceManager.GetString("HtlmUIMUseEmail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Change my configuration options.
        /// </summary>
        internal static string HtmlChangeConfiguration {
            get {
                return ResourceManager.GetString("HtmlChangeConfiguration", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Change my password.
        /// </summary>
        internal static string HtmlChangePassword {
            get {
                return ResourceManager.GetString("HtmlChangePassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Email To.
        /// </summary>
        internal static string HtmlCHOOSEOptionEmail {
            get {
                return ResourceManager.GetString("HtmlCHOOSEOptionEmail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à To confirm your email address, complete the masked portion and click &quot;Send  Code&quot; to receive your code..
        /// </summary>
        internal static string HtmlCHOOSEOptionEmailWarning {
            get {
                return ResourceManager.GetString("HtmlCHOOSEOptionEmailWarning", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à I have no such information.
        /// </summary>
        internal static string HtmlCHOOSEOptionNone {
            get {
                return ResourceManager.GetString("HtmlCHOOSEOptionNone", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Remember my selection.
        /// </summary>
        internal static string HtmlCHOOSEOptionRemember {
            get {
                return ResourceManager.GetString("HtmlCHOOSEOptionRemember", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Send Code.
        /// </summary>
        internal static string HtmlCHOOSEOptionSendCode {
            get {
                return ResourceManager.GetString("HtmlCHOOSEOptionSendCode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Send a SMS to.
        /// </summary>
        internal static string HtmlCHOOSEOptionSMS {
            get {
                return ResourceManager.GetString("HtmlCHOOSEOptionSMS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Use an application (TOTP Application).
        /// </summary>
        internal static string HtmlCHOOSEOptionTOTP {
            get {
                return ResourceManager.GetString("HtmlCHOOSEOptionTOTP", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à wrong Identification, please restart your session.
        /// </summary>
        internal static string HtmlErrorRestartSession {
            get {
                return ResourceManager.GetString("HtmlErrorRestartSession", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Send inscription request.
        /// </summary>
        internal static string HtmlINSRequest {
            get {
                return ResourceManager.GetString("HtmlINSRequest", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Sending your inscription request via email to administrators.
        /// </summary>
        internal static string HtmlINSWaitRequest {
            get {
                return ResourceManager.GetString("HtmlINSWaitRequest", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Scan the QR Code with a TOTP application like Microsoft Authenticator, Google Authenticator for registering your account.
        /// </summary>
        internal static string HtmlLabelWRQRCode {
            get {
                return ResourceManager.GetString("HtmlLabelWRQRCode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Cancel.
        /// </summary>
        internal static string HtmlPWDCancel {
            get {
                return ResourceManager.GetString("HtmlPWDCancel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Current password :.
        /// </summary>
        internal static string HtmlPWDLabelActual {
            get {
                return ResourceManager.GetString("HtmlPWDLabelActual", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à New password :.
        /// </summary>
        internal static string HtmlPWDLabelNew {
            get {
                return ResourceManager.GetString("HtmlPWDLabelNew", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à New password confirmation :.
        /// </summary>
        internal static string HtmlPWDLabelNewConfirmation {
            get {
                return ResourceManager.GetString("HtmlPWDLabelNewConfirmation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Save.
        /// </summary>
        internal static string HtmlPWDSave {
            get {
                return ResourceManager.GetString("HtmlPWDSave", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Default access method :.
        /// </summary>
        internal static string HtmlREGAccessMethod {
            get {
                return ResourceManager.GetString("HtmlREGAccessMethod", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Secret Key :.
        /// </summary>
        internal static string HtmlREGLabelAppKey {
            get {
                return ResourceManager.GetString("HtmlREGLabelAppKey", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Personal email address :.
        /// </summary>
        internal static string HtmlREGLabelMail {
            get {
                return ResourceManager.GetString("HtmlREGLabelMail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Cellphone number :.
        /// </summary>
        internal static string HtmlREGLabelPhoneNumber {
            get {
                return ResourceManager.GetString("HtmlREGLabelPhoneNumber", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Let me choose the best option.
        /// </summary>
        internal static string HtmlREGOptionChooseBest {
            get {
                return ResourceManager.GetString("HtmlREGOptionChooseBest", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Send a email on your personal address.
        /// </summary>
        internal static string HtmlREGOptionEmail {
            get {
                return ResourceManager.GetString("HtmlREGOptionEmail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Send a notification to your cellphone.
        /// </summary>
        internal static string HtmlREGOptionPhone {
            get {
                return ResourceManager.GetString("HtmlREGOptionPhone", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Use a TOTP application.
        /// </summary>
        internal static string HtmlREGOptionTOTP {
            get {
                return ResourceManager.GetString("HtmlREGOptionTOTP", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Reinitialize your key.
        /// </summary>
        internal static string HtmlREGResetQR {
            get {
                return ResourceManager.GetString("HtmlREGResetQR", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Send by email.
        /// </summary>
        internal static string HtmlREGSendQR {
            get {
                return ResourceManager.GetString("HtmlREGSendQR", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Show me the QR Code.
        /// </summary>
        internal static string HtmlREGShowQR {
            get {
                return ResourceManager.GetString("HtmlREGShowQR", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Your secret key has changed !.
        /// </summary>
        internal static string HtmlSecretKeyChanged {
            get {
                return ResourceManager.GetString("HtmlSecretKeyChanged", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à access my options after authentication.
        /// </summary>
        internal static string HtmlUIMAccessOptions {
            get {
                return ResourceManager.GetString("HtmlUIMAccessOptions", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Sign In.
        /// </summary>
        internal static string HtmlUIMConnexion {
            get {
                return ResourceManager.GetString("HtmlUIMConnexion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Disable Multi-Factor authentication.
        /// </summary>
        internal static string HtmlUIMDisableMFA {
            get {
                return ResourceManager.GetString("HtmlUIMDisableMFA", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Inscription request.
        /// </summary>
        internal static string HtmlUIMGotoInscription {
            get {
                return ResourceManager.GetString("HtmlUIMGotoInscription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Change my options.
        /// </summary>
        internal static string HtmlUIMGoToRegistration {
            get {
                return ResourceManager.GetString("HtmlUIMGoToRegistration", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à I do not have the code.
        /// </summary>
        internal static string HtmlUIMNoCode {
            get {
                return ResourceManager.GetString("HtmlUIMNoCode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Ok.
        /// </summary>
        internal static string HtmlUIMOk {
            get {
                return ResourceManager.GetString("HtmlUIMOk", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Use your authenticator application.
        /// </summary>
        internal static string HtmlUIMUseApp {
            get {
                return ResourceManager.GetString("HtmlUIMUseApp", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Check for SMS on your phone.
        /// </summary>
        internal static string HtmlUIMUsePhone {
            get {
                return ResourceManager.GetString("HtmlUIMUsePhone", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à access code for single use : .
        /// </summary>
        internal static string HtmUIMLabelOTP {
            get {
                return ResourceManager.GetString("HtmUIMLabelOTP", resourceCulture);
            }
        }
    }
}
