//------------------------------------------------------------------------------
// <auto-generated>
//     Ce code a été généré par un outil.
//     Version du runtime :4.0.30319.42000
//
//     Les modifications apportées à ce fichier peuvent provoquer un comportement incorrect et seront perdues si
//     le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Neos.IdentityServer.MultiFactor.Resources {
    using System;
    
    
    /// <summary>
    ///   Une classe de ressource fortement typée destinée, entre autres, à la consultation des chaînes localisées.
    /// </summary>
    // Cette classe a été générée automatiquement par la classe StronglyTypedResourceBuilder
    // à l'aide d'un outil, tel que ResGen ou Visual Studio.
    // Pour ajouter ou supprimer un membre, modifiez votre fichier .ResX, puis réexécutez ResGen
    // avec l'option /str ou régénérez votre projet VS.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "15.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class SErrors {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal SErrors() {
        }
        
        /// <summary>
        ///   Retourne l'instance ResourceManager mise en cache utilisée par cette classe.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Neos.IdentityServer.MultiFactor.Resources.SErrors", typeof(SErrors).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Remplace la propriété CurrentUICulture du thread actuel pour toutes
        ///   les recherches de ressources à l'aide de cette classe de ressource fortement typée.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Access to this application requires additional authentication. &lt;br&gt; &lt;br&gt; Click &quot;Activate&quot; to activate your account or Click &quot;Continue&quot;..
        /// </summary>
        public static string ErrorAccountActivate {
            get {
                return ResourceManager.GetString("ErrorAccountActivate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Authorized access ! additional authentication is not activated yet. Please contact your administrators..
        /// </summary>
        public static string ErrorAccountAdminAuthorized {
            get {
                return ResourceManager.GetString("ErrorAccountAdminAuthorized", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Unauthorized access! additional authentication is not yet activated. &lt;br&gt;&lt;br&gt;Please contact your administrators..
        /// </summary>
        public static string ErrorAccountAdminNotEnabled {
            get {
                return ResourceManager.GetString("ErrorAccountAdminNotEnabled", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Access to this application requires additional authentication. &lt;br&gt; &lt;br&gt; Click on &quot;Registration&quot; to continue..
        /// </summary>
        public static string ErrorAccountAuthorized {
            get {
                return ResourceManager.GetString("ErrorAccountAuthorized", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Unauthorized access ! Please contact your administrators.
        /// </summary>
        public static string ErrorAccountNoAccess {
            get {
                return ResourceManager.GetString("ErrorAccountNoAccess", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Access to this application requires additional authentication that is not activated at this time. &lt;br&gt; &lt;br&gt; click on &quot;Registration Request&quot;..
        /// </summary>
        public static string ErrorAccountNotEnabled {
            get {
                return ResourceManager.GetString("ErrorAccountNotEnabled", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Error on authentication process ! 
        ///{0}.
        /// </summary>
        public static string ErrorAuthenticating {
            get {
                return ResourceManager.GetString("ErrorAuthenticating", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Email invalid format !.
        /// </summary>
        public static string ErrorEmailException {
            get {
                return ResourceManager.GetString("ErrorEmailException", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Invalid identification, please restart your session..
        /// </summary>
        public static string ErrorInvalidIdentificationRestart {
            get {
                return ResourceManager.GetString("ErrorInvalidIdentificationRestart", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Incorrect identification, please try again..
        /// </summary>
        public static string ErrorInvalidIdentificationRetry {
            get {
                return ResourceManager.GetString("ErrorInvalidIdentificationRetry", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Invalid Secret Key !.
        /// </summary>
        public static string ErrorInvalidKey {
            get {
                return ResourceManager.GetString("ErrorInvalidKey", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Operation canceled, password invalid !.
        /// </summary>
        public static string ErrorInvalidPassword {
            get {
                return ResourceManager.GetString("ErrorInvalidPassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Incorrect phone number !.
        /// </summary>
        public static string ErrorInvalidPhoneException {
            get {
                return ResourceManager.GetString("ErrorInvalidPhoneException", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Error loading Configuration File : 
        ///{0}.
        /// </summary>
        public static string ErrorLoadingConfigurationFile {
            get {
                return ResourceManager.GetString("ErrorLoadingConfigurationFile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Error loading Configuration File : Not Found !.
        /// </summary>
        public static string ErrorLoadingConfigurationFileNotFound {
            get {
                return ResourceManager.GetString("ErrorLoadingConfigurationFileNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Error loading User Registration ! 
        ///{0}.
        /// </summary>
        public static string ErrorLoadingUserRegistration {
            get {
                return ResourceManager.GetString("ErrorLoadingUserRegistration", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Password for {0} is expired ! Access denied !.
        /// </summary>
        public static string ErrorPasswordExpired {
            get {
                return ResourceManager.GetString("ErrorPasswordExpired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Invalid PIN length, {0} numbers required !.
        /// </summary>
        public static string ErrorPinLength {
            get {
                return ResourceManager.GetString("ErrorPinLength", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Invalid PIN value !.
        /// </summary>
        public static string ErrorPinValue {
            get {
                return ResourceManager.GetString("ErrorPinValue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Error during authentication process ! One Time Password has been played before .
        /// </summary>
        public static string ErrorReplayToken {
            get {
                return ResourceManager.GetString("ErrorReplayToken", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Error when sending identification request !.
        /// </summary>
        public static string ErrorSendingToastInformation {
            get {
                return ResourceManager.GetString("ErrorSendingToastInformation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Error when sending identification request ! please try again..
        /// </summary>
        public static string ErrorSendingToastInformationRetry {
            get {
                return ResourceManager.GetString("ErrorSendingToastInformationRetry", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Window validation time elapsed..
        /// </summary>
        public static string ErrorValidationTimeWindowElapsed {
            get {
                return ResourceManager.GetString("ErrorValidationTimeWindowElapsed", resourceCulture);
            }
        }
    }
}
