//------------------------------------------------------------------------------
// <auto-generated>
//     Ce code a été généré par un outil.
//     Version du runtime :4.0.30319.42000
//
//     Les modifications apportées à ce fichier peuvent provoquer un comportement incorrect et seront perdues si
//     le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Neos.IdentityServer.MultiFactor.Resources {
    using System;
    
    
    /// <summary>
    ///   Une classe de ressource fortement typée destinée, entre autres, à la consultation des chaînes localisées.
    /// </summary>
    // Cette classe a été générée automatiquement par la classe StronglyTypedResourceBuilder
    // à l'aide d'un outil, tel que ResGen ou Visual Studio.
    // Pour ajouter ou supprimer un membre, modifiez votre fichier .ResX, puis réexécutez ResGen
    // avec l'option /str ou régénérez votre projet VS.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "15.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class SHtml {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal SHtml() {
        }
        
        /// <summary>
        ///   Retourne l'instance ResourceManager mise en cache utilisée par cette classe.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Neos.IdentityServer.MultiFactor.Resources.SHtml", typeof(SHtml).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Remplace la propriété CurrentUICulture du thread actuel pour toutes
        ///   les recherches de ressources à l'aide de cette classe de ressource fortement typée.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Use default option.
        /// </summary>
        public static string GLOBALListChoiceDefaultLabel {
            get {
                return ResourceManager.GetString("GLOBALListChoiceDefaultLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Change my configuration options.
        /// </summary>
        public static string HtmlChangeConfiguration {
            get {
                return ResourceManager.GetString("HtmlChangeConfiguration", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Change my password.
        /// </summary>
        public static string HtmlChangePassword {
            get {
                return ResourceManager.GetString("HtmlChangePassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Remember my selection.
        /// </summary>
        public static string HtmlCHOOSEOptionRemember {
            get {
                return ResourceManager.GetString("HtmlCHOOSEOptionRemember", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Default authentication mode.
        /// </summary>
        public static string HtmlCHOOSEOptionRemember2 {
            get {
                return ResourceManager.GetString("HtmlCHOOSEOptionRemember2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Send Code.
        /// </summary>
        public static string HtmlCHOOSEOptionSendCode {
            get {
                return ResourceManager.GetString("HtmlCHOOSEOptionSendCode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Enroll my biometric device.
        /// </summary>
        public static string HtmlEnrollBiometric {
            get {
                return ResourceManager.GetString("HtmlEnrollBiometric", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Enroll my biometric device.
        /// </summary>
        public static string HtmlEnrollBiometrics {
            get {
                return ResourceManager.GetString("HtmlEnrollBiometrics", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Enroll my email address.
        /// </summary>
        public static string HtmlEnrollEmail {
            get {
                return ResourceManager.GetString("HtmlEnrollEmail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Enroll my authentication application .
        /// </summary>
        public static string HtmlEnrollOTP {
            get {
                return ResourceManager.GetString("HtmlEnrollOTP", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Enroll my phone.
        /// </summary>
        public static string HtmlEnrollPhone {
            get {
                return ResourceManager.GetString("HtmlEnrollPhone", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Enroll my PIN code.
        /// </summary>
        public static string HtmlEnrollPinCode {
            get {
                return ResourceManager.GetString("HtmlEnrollPinCode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Set up a PIN.
        /// </summary>
        public static string HtmlEnrollPinTaskLabel {
            get {
                return ResourceManager.GetString("HtmlEnrollPinTaskLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à wrong Identification, please restart your session.
        /// </summary>
        public static string HtmlErrorRestartSession {
            get {
                return ResourceManager.GetString("HtmlErrorRestartSession", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Send request.
        /// </summary>
        public static string HtmlINSRequest {
            get {
                return ResourceManager.GetString("HtmlINSRequest", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Sending your inscription request via email to administrators.
        /// </summary>
        public static string HtmlINSWaitRequest {
            get {
                return ResourceManager.GetString("HtmlINSWaitRequest", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Your account is not validated !&lt;br&gt;
        ///You can try the operation again by selecting &quot;Previous&quot;..
        /// </summary>
        public static string HtmlLabelVERIFYOTPError {
            get {
                return ResourceManager.GetString("HtmlLabelVERIFYOTPError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Finish.
        /// </summary>
        public static string HtmlLabelVERIFYOTPOK {
            get {
                return ResourceManager.GetString("HtmlLabelVERIFYOTPOK", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Previous.
        /// </summary>
        public static string HtmlLabelVERIFYOTPPRIOR {
            get {
                return ResourceManager.GetString("HtmlLabelVERIFYOTPPRIOR", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Your account is validated !&lt;br&gt;
        ///You will be able to use MFA validation in the future..
        /// </summary>
        public static string HtmlLabelVERIFYOTPSuccess {
            get {
                return ResourceManager.GetString("HtmlLabelVERIFYOTPSuccess", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Add a biometric device.
        /// </summary>
        public static string HtmlLabelWRAddBiometrics {
            get {
                return ResourceManager.GetString("HtmlLabelWRAddBiometrics", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à You must activate your biometric device (fingerprint, facial recognition, NFC, etc.) to confirm your identity..
        /// </summary>
        public static string HtmlLabelWRBiometrics {
            get {
                return ResourceManager.GetString("HtmlLabelWRBiometrics", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à You must have an authentication application such as Microsoft Authenticator, Google Authenticator installed on your device before you can continue and register your account.
        /// </summary>
        public static string HtmlLabelWREGOTP {
            get {
                return ResourceManager.GetString("HtmlLabelWREGOTP", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à By continuing, your current key will be invalidated and reset.
        /// </summary>
        public static string HtmlLabelWREGOTPWarning {
            get {
                return ResourceManager.GetString("HtmlLabelWREGOTPWarning", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à You must enter an email address to confirm your identiy. This email must be reachable without needing enterprise verification (personal email address).
        /// </summary>
        public static string HtmlLabelWREmail {
            get {
                return ResourceManager.GetString("HtmlLabelWREmail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Manage your biometrics devices. Select add, replace or delete individual devices..
        /// </summary>
        public static string HtmlLabelWRManageBiometrics {
            get {
                return ResourceManager.GetString("HtmlLabelWRManageBiometrics", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à You must enter your phone number in order to confirm your identity. This phone must be reachable..
        /// </summary>
        public static string HtmlLabelWRPhone {
            get {
                return ResourceManager.GetString("HtmlLabelWRPhone", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à You must enter a secret code ({0} digits) in order to validate your identity. Be sure not to use the codes of your bank card or telephone as well as details concerning your date of birth..
        /// </summary>
        public static string HtmlLabelWRPinCode {
            get {
                return ResourceManager.GetString("HtmlLabelWRPinCode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Scan the QR Code with a TOTP application like Microsoft Authenticator, Google Authenticator for registering your account.
        /// </summary>
        public static string HtmlLabelWRQRCode {
            get {
                return ResourceManager.GetString("HtmlLabelWRQRCode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Continue.
        /// </summary>
        public static string HtmlLabelWVERIFYOTP {
            get {
                return ResourceManager.GetString("HtmlLabelWVERIFYOTP", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à You need to change your password before : &lt;br/&gt; {0}.
        /// </summary>
        public static string HtmlMustChangePassword {
            get {
                return ResourceManager.GetString("HtmlMustChangePassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Cancel.
        /// </summary>
        public static string HtmlPWDCancel {
            get {
                return ResourceManager.GetString("HtmlPWDCancel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Current password.
        /// </summary>
        public static string HtmlPWDLabelActual {
            get {
                return ResourceManager.GetString("HtmlPWDLabelActual", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à New password.
        /// </summary>
        public static string HtmlPWDLabelNew {
            get {
                return ResourceManager.GetString("HtmlPWDLabelNew", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Password confirmation.
        /// </summary>
        public static string HtmlPWDLabelNewConfirmation {
            get {
                return ResourceManager.GetString("HtmlPWDLabelNewConfirmation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Save.
        /// </summary>
        public static string HtmlPWDSave {
            get {
                return ResourceManager.GetString("HtmlPWDSave", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Default access method.
        /// </summary>
        public static string HtmlREGAccessMethod {
            get {
                return ResourceManager.GetString("HtmlREGAccessMethod", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Configuration options.
        /// </summary>
        public static string HtmlREGAccessPageMethods {
            get {
                return ResourceManager.GetString("HtmlREGAccessPageMethods", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Secret Key.
        /// </summary>
        public static string HtmlREGLabelAppKey {
            get {
                return ResourceManager.GetString("HtmlREGLabelAppKey", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Choose the default option.
        /// </summary>
        public static string HtmlREGOptionChooseBest {
            get {
                return ResourceManager.GetString("HtmlREGOptionChooseBest", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Activate.
        /// </summary>
        public static string HtmlUIActivate {
            get {
                return ResourceManager.GetString("HtmlUIActivate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à &lt;br/&gt;
        ///Click &quot;Continue&quot;.
        /// </summary>
        public static string HtmlUIEnrollContinue {
            get {
                return ResourceManager.GetString("HtmlUIEnrollContinue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Access my options after authentication.
        /// </summary>
        public static string HtmlUIMAccessOptions {
            get {
                return ResourceManager.GetString("HtmlUIMAccessOptions", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Verify.
        /// </summary>
        public static string HtmlUIMCheck {
            get {
                return ResourceManager.GetString("HtmlUIMCheck", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Sign In.
        /// </summary>
        public static string HtmlUIMConnexion {
            get {
                return ResourceManager.GetString("HtmlUIMConnexion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Disable Multi-Factor authentication.
        /// </summary>
        public static string HtmlUIMDisableMFA {
            get {
                return ResourceManager.GetString("HtmlUIMDisableMFA", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Inscription request.
        /// </summary>
        public static string HtmlUIMGotoInscription {
            get {
                return ResourceManager.GetString("HtmlUIMGotoInscription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Registration.
        /// </summary>
        public static string HtmlUIMGoToRegistration {
            get {
                return ResourceManager.GetString("HtmlUIMGoToRegistration", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Enter device&apos;s name.
        /// </summary>
        public static string HtmlUIMNickNamesLabel {
            get {
                return ResourceManager.GetString("HtmlUIMNickNamesLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Enter the name of your biometric device or leave the void, then select &quot;Continue&quot;.
        /// </summary>
        public static string HtmlUIMNickNamesMessage {
            get {
                return ResourceManager.GetString("HtmlUIMNickNamesMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Sign in another way.
        /// </summary>
        public static string HtmlUIMNoCode {
            get {
                return ResourceManager.GetString("HtmlUIMNoCode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Ok.
        /// </summary>
        public static string HtmlUIMOk {
            get {
                return ResourceManager.GetString("HtmlUIMOk", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Quit.
        /// </summary>
        public static string HtmlUIMQuit {
            get {
                return ResourceManager.GetString("HtmlUIMQuit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Continue.
        /// </summary>
        public static string HtmlUIMRecordNewKey {
            get {
                return ResourceManager.GetString("HtmlUIMRecordNewKey", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à You must :.
        /// </summary>
        public static string HtmlUIMustPrepareLabel {
            get {
                return ResourceManager.GetString("HtmlUIMustPrepareLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Ignore.
        /// </summary>
        public static string HtmlUINext {
            get {
                return ResourceManager.GetString("HtmlUINext", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Pin code.
        /// </summary>
        public static string HtmlUIPinOptionLabel {
            get {
                return ResourceManager.GetString("HtmlUIPinOptionLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Informations provided :.
        /// </summary>
        public static string HtmlUIResultLabel {
            get {
                return ResourceManager.GetString("HtmlUIResultLabel", resourceCulture);
            }
        }
    }
}
