//------------------------------------------------------------------------------
// <auto-generated>
//     Ce code a été généré par un outil.
//     Version du runtime :4.0.30319.42000
//
//     Les modifications apportées à ce fichier peuvent provoquer un comportement incorrect et seront perdues si
//     le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Neos.IdentityServer.MultiFactor.WebAuthN.Resources {
    using System;
    
    
    /// <summary>
    ///   Une classe de ressource fortement typée destinée, entre autres, à la consultation des chaînes localisées.
    /// </summary>
    // Cette classe a été générée automatiquement par la classe StronglyTypedResourceBuilder
    // à l'aide d'un outil, tel que ResGen ou Visual Studio.
    // Pour ajouter ou supprimer un membre, modifiez votre fichier .ResX, puis réexécutez ResGen
    // avec l'option /str ou régénérez votre projet VS.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "15.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class CSHtml {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal CSHtml() {
        }
        
        /// <summary>
        ///   Retourne l'instance ResourceManager mise en cache utilisée par cette classe.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Neos.IdentityServer.MultiFactor.WebAuthN.Resources.CSHtml", typeof(CSHtml).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Remplace la propriété CurrentUICulture du thread actuel pour toutes
        ///   les recherches de ressources à l'aide de cette classe de ressource fortement typée.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Error during authentication process ! Security Descriptor Data has been been used before !.
        /// </summary>
        internal static string BIOERRORAUTHREPLAY {
            get {
                return ResourceManager.GetString("BIOERRORAUTHREPLAY", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Activate your biometric device.
        /// </summary>
        internal static string BIOUICFGLabel {
            get {
                return ResourceManager.GetString("BIOUICFGLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Use my biometric device.
        /// </summary>
        internal static string BIOUIChoiceLabel {
            get {
                return ResourceManager.GetString("BIOUIChoiceLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Use my biometric device.
        /// </summary>
        internal static string BIOUIConfigLabel {
            get {
                return ResourceManager.GetString("BIOUIConfigLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Delete this device.
        /// </summary>
        internal static string BIOUIEnrollDeleteLinkLabel {
            get {
                return ResourceManager.GetString("BIOUIEnrollDeleteLinkLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Manage my biometrics devices.
        /// </summary>
        internal static string BIOUIEnrollManageLinkLabel {
            get {
                return ResourceManager.GetString("BIOUIEnrollManageLinkLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Register a biometric device.
        /// </summary>
        internal static string BIOUIEnrollTaskLabel {
            get {
                return ResourceManager.GetString("BIOUIEnrollTaskLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Account verified &lt;br&gt;&lt;br&gt;You can use your biometric device to authenticate.
        /// </summary>
        internal static string BIOUIEnrollValidatedLabel {
            get {
                return ResourceManager.GetString("BIOUIEnrollValidatedLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Use my biometric device.
        /// </summary>
        internal static string BIOUIListChoiceLabel {
            get {
                return ResourceManager.GetString("BIOUIListChoiceLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Biometric device.
        /// </summary>
        internal static string BIOUIListOptionLabel {
            get {
                return ResourceManager.GetString("BIOUIListOptionLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Touch or Scan with your biometric device.
        /// </summary>
        internal static string BIOUIMessage {
            get {
                return ResourceManager.GetString("BIOUIMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Use your biometric device.
        /// </summary>
        internal static string BIOUIOTPLabel {
            get {
                return ResourceManager.GetString("BIOUIOTPLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Manage your biometrics devices. Select add, replace or delete individual devices..
        /// </summary>
        internal static string BIOUIWIZComment {
            get {
                return ResourceManager.GetString("BIOUIWIZComment", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Enroll your biometric device.
        /// </summary>
        internal static string BIOUIWIZLabel {
            get {
                return ResourceManager.GetString("BIOUIWIZLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Enroll my biometric device.
        /// </summary>
        internal static string BIOWIZEnroll {
            get {
                return ResourceManager.GetString("BIOWIZEnroll", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Biometrics Multi-Factor Provider.
        /// </summary>
        internal static string PROVIDERBIODESCRIPTION {
            get {
                return ResourceManager.GetString("PROVIDERBIODESCRIPTION", resourceCulture);
            }
        }
    }
}
