//------------------------------------------------------------------------------
// <auto-generated>
//     Ce code a été généré par un outil.
//     Version du runtime :4.0.30319.42000
//
//     Les modifications apportées à ce fichier peuvent provoquer un comportement incorrect et seront perdues si
//     le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Neos.IdentityServer.MultiFactor.Common.Resources {
    using System;
    
    
    /// <summary>
    ///   Une classe de ressource fortement typée destinée, entre autres, à la consultation des chaînes localisées.
    /// </summary>
    // Cette classe a été générée automatiquement par la classe StronglyTypedResourceBuilder
    // à l'aide d'un outil, tel que ResGen ou Visual Studio.
    // Pour ajouter ou supprimer un membre, modifiez votre fichier .ResX, puis réexécutez ResGen
    // avec l'option /str ou régénérez votre projet VS.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "15.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class CSHtml {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal CSHtml() {
        }
        
        /// <summary>
        ///   Retourne l'instance ResourceManager mise en cache utilisée par cette classe.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Neos.IdentityServer.MultiFactor.Common.Resources.CSHtml", typeof(CSHtml).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Remplace la propriété CurrentUICulture du thread actuel pour toutes
        ///   les recherches de ressources à l'aide de cette classe de ressource fortement typée.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à We sent an email containing the registration information..
        /// </summary>
        internal static string ADMINInscriptionEmail {
            get {
                return ResourceManager.GetString("ADMINInscriptionEmail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à We sent you an email containing your secret key. (confidential).
        /// </summary>
        internal static string ADMINKeyEmail {
            get {
                return ResourceManager.GetString("ADMINKeyEmail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Use default option.
        /// </summary>
        internal static string GLOBALListChoiceDefaultLabel {
            get {
                return ResourceManager.GetString("GLOBALListChoiceDefaultLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Enter PIN.
        /// </summary>
        internal static string GLOBALPINLabel {
            get {
                return ResourceManager.GetString("GLOBALPINLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Enter your PIN code.
        /// </summary>
        internal static string GLOBALPINMessage {
            get {
                return ResourceManager.GetString("GLOBALPINMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Enroll your Pin code.
        /// </summary>
        internal static string GLOBALUIPINLabel {
            get {
                return ResourceManager.GetString("GLOBALUIPINLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à (The data is transmitted over the internet).
        /// </summary>
        internal static string GLOBALWarnOverNetwork {
            get {
                return ResourceManager.GetString("GLOBALWarnOverNetwork", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à (authentication is performed by a third party).
        /// </summary>
        internal static string GLOBALWarnThirdParty {
            get {
                return ResourceManager.GetString("GLOBALWarnThirdParty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Personal email address.
        /// </summary>
        internal static string MAILUICFGLabel {
            get {
                return ResourceManager.GetString("MAILUICFGLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Receive an email on my personal address.
        /// </summary>
        internal static string MAILUIChoiceLabel {
            get {
                return ResourceManager.GetString("MAILUIChoiceLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Send an email on my personal address.
        /// </summary>
        internal static string MAILUIConfigLabel {
            get {
                return ResourceManager.GetString("MAILUIConfigLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Send an email on my personal address {0}.
        /// </summary>
        internal static string MAILUIConfigLabel2 {
            get {
                return ResourceManager.GetString("MAILUIConfigLabel2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Receive an email on my personal address.
        /// </summary>
        internal static string MAILUIListChoiceLabel {
            get {
                return ResourceManager.GetString("MAILUIListChoiceLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Personal email address.
        /// </summary>
        internal static string MAILUIListOptionLabel {
            get {
                return ResourceManager.GetString("MAILUIListOptionLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à We sent an email containing a verification code..
        /// </summary>
        internal static string MAILUIMessage {
            get {
                return ResourceManager.GetString("MAILUIMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Enter Code.
        /// </summary>
        internal static string MAILUIOTPLabel {
            get {
                return ResourceManager.GetString("MAILUIOTPLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Enroll your email address.
        /// </summary>
        internal static string MAILUIWIZLabel {
            get {
                return ResourceManager.GetString("MAILUIWIZLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Single use access code.
        /// </summary>
        internal static string OTPUICFGLabel {
            get {
                return ResourceManager.GetString("OTPUICFGLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Use my authentication application.
        /// </summary>
        internal static string OTPUIChoiceLabel {
            get {
                return ResourceManager.GetString("OTPUIChoiceLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Use my authentication application.
        /// </summary>
        internal static string OTPUIConfigLabel {
            get {
                return ResourceManager.GetString("OTPUIConfigLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Use your authentication application.
        /// </summary>
        internal static string OTPUIListChoiceLabel {
            get {
                return ResourceManager.GetString("OTPUIListChoiceLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Authentication application.
        /// </summary>
        internal static string OTPUIListOptionLabel {
            get {
                return ResourceManager.GetString("OTPUIListOptionLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Enter the verification code displayed in the authenticator app on your mobile device..
        /// </summary>
        internal static string OTPUIMessage {
            get {
                return ResourceManager.GetString("OTPUIMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Enter Code.
        /// </summary>
        internal static string OTPUIOTPLabel {
            get {
                return ResourceManager.GetString("OTPUIOTPLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Enroll Authenticator App.
        /// </summary>
        internal static string OTPUIWIZLabel {
            get {
                return ResourceManager.GetString("OTPUIWIZLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Phone number.
        /// </summary>
        internal static string SMSUICFGLabel {
            get {
                return ResourceManager.GetString("SMSUICFGLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Send a message on my mobile.
        /// </summary>
        internal static string SMSUIChoiceLabel {
            get {
                return ResourceManager.GetString("SMSUIChoiceLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Return the code received on my mobile.
        /// </summary>
        internal static string SMSUIChoiceLabel2 {
            get {
                return ResourceManager.GetString("SMSUIChoiceLabel2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Text message on my mobile phone.
        /// </summary>
        internal static string SMSUIConfigLabel {
            get {
                return ResourceManager.GetString("SMSUIConfigLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Text message on my mobile phone {0}.
        /// </summary>
        internal static string SMSUIConfigLabel2 {
            get {
                return ResourceManager.GetString("SMSUIConfigLabel2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Receive a message on my mobile phone.
        /// </summary>
        internal static string SMSUIListChoiceLabel {
            get {
                return ResourceManager.GetString("SMSUIListChoiceLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Mobile phone authentication.
        /// </summary>
        internal static string SMSUIListOptionLabel {
            get {
                return ResourceManager.GetString("SMSUIListOptionLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à We sent an SMS containing a verification code. {0}.
        /// </summary>
        internal static string SMSUIMessage {
            get {
                return ResourceManager.GetString("SMSUIMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Access code received by phone.
        /// </summary>
        internal static string SMSUIOTPLabel {
            get {
                return ResourceManager.GetString("SMSUIOTPLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Enroll your mobile.
        /// </summary>
        internal static string SMSUIWIZLabel {
            get {
                return ResourceManager.GetString("SMSUIWIZLabel", resourceCulture);
            }
        }
    }
}
