//------------------------------------------------------------------------------
// <auto-generated>
//     Ce code a été généré par un outil.
//     Version du runtime :4.0.30319.42000
//
//     Les modifications apportées à ce fichier peuvent provoquer un comportement incorrect et seront perdues si
//     le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Neos.IdentityServer.MultiFactor.SMS.Resources {
    using System;
    
    
    /// <summary>
    ///   Une classe de ressource fortement typée destinée, entre autres, à la consultation des chaînes localisées.
    /// </summary>
    // Cette classe a été générée automatiquement par la classe StronglyTypedResourceBuilder
    // à l'aide d'un outil, tel que ResGen ou Visual Studio.
    // Pour ajouter ou supprimer un membre, modifiez votre fichier .ResX, puis réexécutez ResGen
    // avec l'option /str ou régénérez votre projet VS.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class html_strings {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal html_strings() {
        }
        
        /// <summary>
        ///   Retourne l'instance ResourceManager mise en cache utilisée par cette classe.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Neos.IdentityServer.MultiFactor.SMS.Resources.html_strings", typeof(html_strings).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Remplace la propriété CurrentUICulture du thread actuel pour toutes
        ///   les recherches de ressources à l'aide de cette classe de ressource fortement typée.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Use default option.
        /// </summary>
        internal static string GLOBALListChoiceDefaultLabel {
            get {
                return ResourceManager.GetString("GLOBALListChoiceDefaultLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à (data is transmitted over internet).
        /// </summary>
        internal static string GLOBALWarnOverNetwork {
            get {
                return ResourceManager.GetString("GLOBALWarnOverNetwork", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à (authentication is performed by a third party).
        /// </summary>
        internal static string GLOBALWarnThirdParty {
            get {
                return ResourceManager.GetString("GLOBALWarnThirdParty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Phone number.
        /// </summary>
        internal static string SMSUICFGLabel {
            get {
                return ResourceManager.GetString("SMSUICFGLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Send a code to my mobile.
        /// </summary>
        internal static string SMSUIChoiceLabel {
            get {
                return ResourceManager.GetString("SMSUIChoiceLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Return the code received on my mobile.
        /// </summary>
        internal static string SMSUIChoiceLabel2 {
            get {
                return ResourceManager.GetString("SMSUIChoiceLabel2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Text message on my mobile phone.
        /// </summary>
        internal static string SMSUIConfigLabel {
            get {
                return ResourceManager.GetString("SMSUIConfigLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Text message on my mobile phone {0}.
        /// </summary>
        internal static string SMSUIConfigLabel2 {
            get {
                return ResourceManager.GetString("SMSUIConfigLabel2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Receive a message on my mobile phone.
        /// </summary>
        internal static string SMSUIListChoiceLabel {
            get {
                return ResourceManager.GetString("SMSUIListChoiceLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Personal mobile phone.
        /// </summary>
        internal static string SMSUIListOptionLabel {
            get {
                return ResourceManager.GetString("SMSUIListOptionLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Access my configuration options.
        /// </summary>
        internal static string SMSUIManagement {
            get {
                return ResourceManager.GetString("SMSUIManagement", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à We sent an SMS containing a verification code. {0}.
        /// </summary>
        internal static string SMSUIMessage {
            get {
                return ResourceManager.GetString("SMSUIMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Enter Code.
        /// </summary>
        internal static string SMSUIOTPLabel {
            get {
                return ResourceManager.GetString("SMSUIOTPLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Enroll your mobile.
        /// </summary>
        internal static string SMSUIWIZLabel {
            get {
                return ResourceManager.GetString("SMSUIWIZLabel", resourceCulture);
            }
        }
    }
}
