//------------------------------------------------------------------------------
// <auto-generated>
//     Ce code a été généré par un outil.
//     Version du runtime :4.0.30319.42000
//
//     Les modifications apportées à ce fichier peuvent provoquer un comportement incorrect et seront perdues si
//     le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Neos.IdentityServer.MultiFactor.SAS.Resources {
    using System;
    
    
    /// <summary>
    ///   Une classe de ressource fortement typée destinée, entre autres, à la consultation des chaînes localisées.
    /// </summary>
    // Cette classe a été générée automatiquement par la classe StronglyTypedResourceBuilder
    // à l'aide d'un outil, tel que ResGen ou Visual Studio.
    // Pour ajouter ou supprimer un membre, modifiez votre fichier .ResX, puis réexécutez ResGen
    // avec l'option /str ou régénérez votre projet VS.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "15.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class SSAS {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal SSAS() {
        }
        
        /// <summary>
        ///   Retourne l'instance ResourceManager mise en cache utilisée par cette classe.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Neos.IdentityServer.MultiFactor.SAS.Resources.SSAS", typeof(SSAS).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Remplace la propriété CurrentUICulture du thread actuel pour toutes
        ///   les recherches de ressources à l'aide de cette classe de ressource fortement typée.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Phone Number.
        /// </summary>
        internal static string GLOBALCFGLabel {
            get {
                return ResourceManager.GetString("GLOBALCFGLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Use default Azure option.
        /// </summary>
        internal static string GLOBALListChoiceDefaultLabel {
            get {
                return ResourceManager.GetString("GLOBALListChoiceDefaultLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Use Azure authentication options.
        /// </summary>
        internal static string GLOBALListChoiceLabel {
            get {
                return ResourceManager.GetString("GLOBALListChoiceLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Azure authentication options.
        /// </summary>
        internal static string GLOBALListOptionLabel {
            get {
                return ResourceManager.GetString("GLOBALListOptionLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Enroll my Azure options.
        /// </summary>
        internal static string GLOBALManagement {
            get {
                return ResourceManager.GetString("GLOBALManagement", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Single use access code.
        /// </summary>
        internal static string GLOBALOTPLabel {
            get {
                return ResourceManager.GetString("GLOBALOTPLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à (data is transmitted over internet).
        /// </summary>
        internal static string GLOBALWarnOverNetwork {
            get {
                return ResourceManager.GetString("GLOBALWarnOverNetwork", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à (authentication is performed by Microsoft).
        /// </summary>
        internal static string GLOBALWarnThirdParty {
            get {
                return ResourceManager.GetString("GLOBALWarnThirdParty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Enroll your mobile.
        /// </summary>
        internal static string GLOBALWIZLabel {
            get {
                return ResourceManager.GetString("GLOBALWIZLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Send a notification to my mobile (Azure).
        /// </summary>
        internal static string NOTIFChoiceLabel {
            get {
                return ResourceManager.GetString("NOTIFChoiceLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Notification on your authentication application.
        /// </summary>
        internal static string NOTIFConfigLabel {
            get {
                return ResourceManager.GetString("NOTIFConfigLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à We have sent a notification to your mobile device. Answer to continue..
        /// </summary>
        internal static string NOTIFMessage {
            get {
                return ResourceManager.GetString("NOTIFMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Use my authentication application (Azure).
        /// </summary>
        internal static string OTPChoiceLabel {
            get {
                return ResourceManager.GetString("OTPChoiceLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Use your authentication application.
        /// </summary>
        internal static string OTPConfigLabel {
            get {
                return ResourceManager.GetString("OTPConfigLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Enter the verification code for your mobile application..
        /// </summary>
        internal static string OTPMessage {
            get {
                return ResourceManager.GetString("OTPMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Microsoft Azure Multi-Factor Provider.
        /// </summary>
        internal static string PROVIDERAZURESDESCRIPTION {
            get {
                return ResourceManager.GetString("PROVIDERAZURESDESCRIPTION", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Send a code to my mobile (Azure).
        /// </summary>
        internal static string SMSChoiceLabel {
            get {
                return ResourceManager.GetString("SMSChoiceLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Text message on my mobile phone.
        /// </summary>
        internal static string SMSConfigLabel {
            get {
                return ResourceManager.GetString("SMSConfigLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Text message on my mobile phone {0}.
        /// </summary>
        internal static string SMSConfigLabel2 {
            get {
                return ResourceManager.GetString("SMSConfigLabel2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à We sent an SMS containing a verification code. {0}.
        /// </summary>
        internal static string SMSMessage {
            get {
                return ResourceManager.GetString("SMSMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Call my mobile phone (Azure).
        /// </summary>
        internal static string VOICE1ChoiceLabel {
            get {
                return ResourceManager.GetString("VOICE1ChoiceLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Voice call on your mobile.
        /// </summary>
        internal static string VOICE1ConfigLabel {
            get {
                return ResourceManager.GetString("VOICE1ConfigLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Voice call on your mobile {0}.
        /// </summary>
        internal static string VOICE1ConfigLabel2 {
            get {
                return ResourceManager.GetString("VOICE1ConfigLabel2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à We call your phone {0}. Answer to continue..
        /// </summary>
        internal static string VOICE1Message {
            get {
                return ResourceManager.GetString("VOICE1Message", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Call my secondary phone (Azure).
        /// </summary>
        internal static string VOICE2ChoiceLabel {
            get {
                return ResourceManager.GetString("VOICE2ChoiceLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Voice call on my secondary mobile phone.
        /// </summary>
        internal static string VOICE2ConfigLabel {
            get {
                return ResourceManager.GetString("VOICE2ConfigLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Voice call on my secondary mobile phone {0}.
        /// </summary>
        internal static string VOICE2ConfigLabel2 {
            get {
                return ResourceManager.GetString("VOICE2ConfigLabel2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à We call your secondary phone {0}. Answer to continue..
        /// </summary>
        internal static string VOICE2Message {
            get {
                return ResourceManager.GetString("VOICE2Message", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Call my office phone (Azure).
        /// </summary>
        internal static string VOICE3ChoiceLabel {
            get {
                return ResourceManager.GetString("VOICE3ChoiceLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Voice call on your office phone.
        /// </summary>
        internal static string VOICE3ConfigLabel {
            get {
                return ResourceManager.GetString("VOICE3ConfigLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Voice call on your office phone {0}.
        /// </summary>
        internal static string VOICE3ConfigLabel2 {
            get {
                return ResourceManager.GetString("VOICE3ConfigLabel2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à We call your office phone {0}. Answer to continue..
        /// </summary>
        internal static string VOICE3Message {
            get {
                return ResourceManager.GetString("VOICE3Message", resourceCulture);
            }
        }
    }
}
