//------------------------------------------------------------------------------
// <auto-generated>
//     Ce code a été généré par un outil.
//     Version du runtime :4.0.30319.42000
//
//     Les modifications apportées à ce fichier peuvent provoquer un comportement incorrect et seront perdues si
//     le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Neos.IdentityServer.Console.Resources {
    using System;
    
    
    /// <summary>
    ///   Une classe de ressource fortement typée destinée, entre autres, à la consultation des chaînes localisées.
    /// </summary>
    // Cette classe a été générée automatiquement par la classe StronglyTypedResourceBuilder
    // à l'aide d'un outil, tel que ResGen ou Visual Studio.
    // Pour ajouter ou supprimer un membre, modifiez votre fichier .ResX, puis réexécutez ResGen
    // avec l'option /str ou régénérez votre projet VS.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "15.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Neos_IdentityServer_Console_Ctrls {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Neos_IdentityServer_Console_Ctrls() {
        }
        
        /// <summary>
        ///   Retourne l'instance ResourceManager mise en cache utilisée par cette classe.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Neos.IdentityServer.Console.Resources.Neos.IdentityServer.Console.Ctrls", typeof(Neos_IdentityServer_Console_Ctrls).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Remplace la propriété CurrentUICulture du thread actuel pour toutes
        ///   les recherches de ressources à l'aide de cette classe de ressource fortement typée.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Restart all federation services.
        /// </summary>
        internal static string CRTLADFSRESTARTFARMSERVICES {
            get {
                return ResourceManager.GetString("CRTLADFSRESTARTFARMSERVICES", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Restart fedeartion services.
        /// </summary>
        internal static string CRTLADFSRESTARTSERVICES {
            get {
                return ResourceManager.GetString("CRTLADFSRESTARTSERVICES", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Start fedeartion services.
        /// </summary>
        internal static string CRTLADFSSTARTSERVICES {
            get {
                return ResourceManager.GetString("CRTLADFSSTARTSERVICES", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Stop federation services.
        /// </summary>
        internal static string CRTLADFSSTOPSERVICES {
            get {
                return ResourceManager.GetString("CRTLADFSSTOPSERVICES", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Registration Notifications.
        /// </summary>
        internal static string CTRGLMANAGEREG {
            get {
                return ResourceManager.GetString("CTRGLMANAGEREG", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à End.
        /// </summary>
        internal static string CTRGLMANAGEREGEND {
            get {
                return ResourceManager.GetString("CTRGLMANAGEREGEND", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Start.
        /// </summary>
        internal static string CTRGLMANAGEREGSTART {
            get {
                return ResourceManager.GetString("CTRGLMANAGEREGSTART", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Access account.
        /// </summary>
        internal static string CTRLADACCOUNT {
            get {
                return ResourceManager.GetString("CTRLADACCOUNT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Invalid ADDS attribute for check date !.
        /// </summary>
        internal static string CTRLADATCHECKDATEERROR {
            get {
                return ResourceManager.GetString("CTRLADATCHECKDATEERROR", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Invalid ADDS attribute for Enbaled !.
        /// </summary>
        internal static string CTRLADATENABLEDERROR {
            get {
                return ResourceManager.GetString("CTRLADATENABLEDERROR", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Invalid ADDS attribute for method !.
        /// </summary>
        internal static string CTRLADATMETHODERROR {
            get {
                return ResourceManager.GetString("CTRLADATMETHODERROR", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Invalid ADDS attribute for specific method !.
        /// </summary>
        internal static string CTRLADATOVERRIDEERROR {
            get {
                return ResourceManager.GetString("CTRLADATOVERRIDEERROR", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Invalid ADDS attribute for pin code !.
        /// </summary>
        internal static string CTRLADATPINERROR {
            get {
                return ResourceManager.GetString("CTRLADATPINERROR", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Invalid ADDS attribute for RSA certificate !.
        /// </summary>
        internal static string CTRLADATRSACERTERROR {
            get {
                return ResourceManager.GetString("CTRLADATRSACERTERROR", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Invalid ADDS account !.
        /// </summary>
        internal static string CTRLADATTACCOUNT {
            get {
                return ResourceManager.GetString("CTRLADATTACCOUNT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Invalid ADDS domain address !.
        /// </summary>
        internal static string CTRLADATTDOMAIN {
            get {
                return ResourceManager.GetString("CTRLADATTDOMAIN", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Invalid ADDS attribute for Email address !.
        /// </summary>
        internal static string CTRLADATTEMAILERROR {
            get {
                return ResourceManager.GetString("CTRLADATTEMAILERROR", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Secret key.
        /// </summary>
        internal static string CTRLADATTKEY {
            get {
                return ResourceManager.GetString("CTRLADATTKEY", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Invalid ADDS attribute for Key !.
        /// </summary>
        internal static string CTRLADATTKEYERROR {
            get {
                return ResourceManager.GetString("CTRLADATTKEYERROR", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à E-mail adress.
        /// </summary>
        internal static string CTRLADATTMAIL {
            get {
                return ResourceManager.GetString("CTRLADATTMAIL", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Default MFA method.
        /// </summary>
        internal static string CTRLADATTMETHOD {
            get {
                return ResourceManager.GetString("CTRLADATTMETHOD", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Override MFA method.
        /// </summary>
        internal static string CTRLADATTOVERRIDE {
            get {
                return ResourceManager.GetString("CTRLADATTOVERRIDE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Invalid ADDS password !.
        /// </summary>
        internal static string CTRLADATTPASSWORD {
            get {
                return ResourceManager.GetString("CTRLADATTPASSWORD", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Mobile phone.
        /// </summary>
        internal static string CTRLADATTPHONE {
            get {
                return ResourceManager.GetString("CTRLADATTPHONE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Invalid ADDS attribute for Phone Number !.
        /// </summary>
        internal static string CTRLADATTPHONEERROR {
            get {
                return ResourceManager.GetString("CTRLADATTPHONEERROR", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Pin Code.
        /// </summary>
        internal static string CTRLADATTPIN {
            get {
                return ResourceManager.GetString("CTRLADATTPIN", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à WebAuthN Public Key.
        /// </summary>
        internal static string CTRLADATTPUBLICKEY {
            get {
                return ResourceManager.GetString("CTRLADATTPUBLICKEY", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Active Directory Attributes Settings.
        /// </summary>
        internal static string CTRLADATTRIBUTES {
            get {
                return ResourceManager.GetString("CTRLADATTRIBUTES", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à RSA User Certificate .
        /// </summary>
        internal static string CTRLADATTRSACERT {
            get {
                return ResourceManager.GetString("CTRLADATTRSACERT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à User activation status.
        /// </summary>
        internal static string CTRLADATTSTATUS {
            get {
                return ResourceManager.GetString("CTRLADATTSTATUS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à TOTP Verification date.
        /// </summary>
        internal static string CTRLADATTVALIDATION {
            get {
                return ResourceManager.GetString("CTRLADATTVALIDATION", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à TOTP Validity date.
        /// </summary>
        internal static string CTRLADATTVALIDITY {
            get {
                return ResourceManager.GetString("CTRLADATTVALIDITY", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Invalid ADDS attribute for validity date !.
        /// </summary>
        internal static string CTRLADATVALIDITYDATEERROR {
            get {
                return ResourceManager.GetString("CTRLADATVALIDITYDATEERROR", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Unable to connect on ADDS forest/Domain !.
        /// </summary>
        internal static string CTRLADCONNECTIONERROR {
            get {
                return ResourceManager.GetString("CTRLADCONNECTIONERROR", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Connection on ADDS Forest/Domain operational !.
        /// </summary>
        internal static string CTRLADCONNECTIONOK {
            get {
                return ResourceManager.GetString("CTRLADCONNECTIONOK", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Domain name.
        /// </summary>
        internal static string CTRLADDOMAIN {
            get {
                return ResourceManager.GetString("CTRLADDOMAIN", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Enable MFA.
        /// </summary>
        internal static string CTRLADFSACTIVATEMFA {
            get {
                return ResourceManager.GetString("CTRLADFSACTIVATEMFA", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Disable MFA.
        /// </summary>
        internal static string CTRLADFSDEACTIVATEMFA {
            get {
                return ResourceManager.GetString("CTRLADFSDEACTIVATEMFA", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Use secure LDAP connections (LDAPS).
        /// </summary>
        internal static string CTRLADLDAPSSL {
            get {
                return ResourceManager.GetString("CTRLADLDAPSSL", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Password.
        /// </summary>
        internal static string CTRLADPASSWORD {
            get {
                return ResourceManager.GetString("CTRLADPASSWORD", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Active Directory &quot;SuperUser&quot; Credentials.
        /// </summary>
        internal static string CTRLADSUPERACCOUNT {
            get {
                return ResourceManager.GetString("CTRLADSUPERACCOUNT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à ADDS Schema 2016++.
        /// </summary>
        internal static string CTRLADTEMPLATE2016 {
            get {
                return ResourceManager.GetString("CTRLADTEMPLATE2016", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Error when loading &quot;2016&quot; template, you must update manually your attributes !.
        /// </summary>
        internal static string CTRLADTEMPLATE2016ERROR {
            get {
                return ResourceManager.GetString("CTRLADTEMPLATE2016ERROR", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à ADDS Schema 2012--.
        /// </summary>
        internal static string CTRLADTEMPLATEBASE {
            get {
                return ResourceManager.GetString("CTRLADTEMPLATEBASE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Error when loading &quot;Default&quot; template, you must update manually your attributes !.
        /// </summary>
        internal static string CTRLADTEMPLATEBASEERROR {
            get {
                return ResourceManager.GetString("CTRLADTEMPLATEBASEERROR", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à ADDS Schema MFA.
        /// </summary>
        internal static string CTRLADTEMPLATEMFA {
            get {
                return ResourceManager.GetString("CTRLADTEMPLATEMFA", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Error when loading &quot;MFA&quot; template, you must update manually your attributes !.
        /// </summary>
        internal static string CTRLADTEMPLATEMFAERROR {
            get {
                return ResourceManager.GetString("CTRLADTEMPLATEMFAERROR", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Test.
        /// </summary>
        internal static string CTRLADTEST {
            get {
                return ResourceManager.GetString("CTRLADTEST", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à General Security Properties.
        /// </summary>
        internal static string CTRLADTITLECONFIG {
            get {
                return ResourceManager.GetString("CTRLADTITLECONFIG", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Use Active Directory Configuration.
        /// </summary>
        internal static string CTRLADUSEADDS {
            get {
                return ResourceManager.GetString("CTRLADUSEADDS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Azure Tenant.
        /// </summary>
        internal static string CTRLAZURETENANTID {
            get {
                return ResourceManager.GetString("CTRLAZURETENANTID", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Azure Certificate ThumbPrint.
        /// </summary>
        internal static string CTRLAZURETHUMPRINT {
            get {
                return ResourceManager.GetString("CTRLAZURETHUMPRINT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Cancel.
        /// </summary>
        internal static string CTRLCANCEL {
            get {
                return ResourceManager.GetString("CTRLCANCEL", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Invalid Extension ! cannot be loaded !.
        /// </summary>
        internal static string CTRLCUSTOMKEYSERROR {
            get {
                return ResourceManager.GetString("CTRLCUSTOMKEYSERROR", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Use Custom Repository.
        /// </summary>
        internal static string CTRLCUSTOMUSING {
            get {
                return ResourceManager.GetString("CTRLCUSTOMUSING", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Data Repository (full class).
        /// </summary>
        internal static string CTRLDATAREPOASSEMBLY {
            get {
                return ResourceManager.GetString("CTRLDATAREPOASSEMBLY", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Max retries allowed.
        /// </summary>
        internal static string CTRLDLGMAXRETRIES {
            get {
                return ResourceManager.GetString("CTRLDLGMAXRETRIES", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Show Google search.
        /// </summary>
        internal static string CTRLGLALLOWGOOGLESEARCH {
            get {
                return ResourceManager.GetString("CTRLGLALLOWGOOGLESEARCH", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Company Name.
        /// </summary>
        internal static string CTRLGLCOMANYNAME {
            get {
                return ResourceManager.GetString("CTRLGLCOMANYNAME", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Administrative contact (email).
        /// </summary>
        internal static string CTRLGLCONTACT {
            get {
                return ResourceManager.GetString("CTRLGLCONTACT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Default country code.
        /// </summary>
        internal static string CTRLGLCONTRYCODE {
            get {
                return ResourceManager.GetString("CTRLGLCONTRYCODE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Validation time (in seconds).
        /// </summary>
        internal static string CTRLGLDELVERY {
            get {
                return ResourceManager.GetString("CTRLGLDELVERY", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Duration.
        /// </summary>
        internal static string CTRLGLDURATION {
            get {
                return ResourceManager.GetString("CTRLGLDURATION", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Registration Wizards.
        /// </summary>
        internal static string CTRLGLENROLLWIZ {
            get {
                return ResourceManager.GetString("CTRLGLENROLLWIZ", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Hash algorithm.
        /// </summary>
        internal static string CTRLGLHASH {
            get {
                return ResourceManager.GetString("CTRLGLHASH", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Invalid email format for admin contact !.
        /// </summary>
        internal static string CTRLGLINVALIDEMAILCONTACT {
            get {
                return ResourceManager.GetString("CTRLGLINVALIDEMAILCONTACT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à User can select default provider.
        /// </summary>
        internal static string CTRLGLMANAGEKMSOO {
            get {
                return ResourceManager.GetString("CTRLGLMANAGEKMSOO", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Notify users after configuration changes.
        /// </summary>
        internal static string CTRLGLMANAGENOTIFS {
            get {
                return ResourceManager.GetString("CTRLGLMANAGENOTIFS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à User management options.
        /// </summary>
        internal static string CTRLGLMANAGEOPTIONS {
            get {
                return ResourceManager.GetString("CTRLGLMANAGEOPTIONS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Options Management.
        /// </summary>
        internal static string CTRLGLMANAGEOPTS {
            get {
                return ResourceManager.GetString("CTRLGLMANAGEOPTS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Password management.
        /// </summary>
        internal static string CTRLGLMANAGEPWD {
            get {
                return ResourceManager.GetString("CTRLGLMANAGEPWD", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Authorized code history.
        /// </summary>
        internal static string CTRLGLMAXCODES {
            get {
                return ResourceManager.GetString("CTRLGLMAXCODES", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Digits.
        /// </summary>
        internal static string CTRLGLMAXDIGITS {
            get {
                return ResourceManager.GetString("CTRLGLMAXDIGITS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à User Registration.
        /// </summary>
        internal static string CTRLGLMFAREGISTER {
            get {
                return ResourceManager.GetString("CTRLGLMFAREGISTER", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Administrative - Registration verified by support.
        /// </summary>
        internal static string CTRLGLMFAREGISTER1 {
            get {
                return ResourceManager.GetString("CTRLGLMFAREGISTER1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à User - Registration made by the user.
        /// </summary>
        internal static string CTRLGLMFAREGISTER2 {
            get {
                return ResourceManager.GetString("CTRLGLMFAREGISTER2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Unmanaged - Contact Support.
        /// </summary>
        internal static string CTRLGLMFAREGISTER3 {
            get {
                return ResourceManager.GetString("CTRLGLMFAREGISTER3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Mandatory - Registration made by support.
        /// </summary>
        internal static string CTRLGLMFAREGISTER4 {
            get {
                return ResourceManager.GetString("CTRLGLMFAREGISTER4", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à MFA Status.
        /// </summary>
        internal static string CTRLGLMFASTATUS {
            get {
                return ResourceManager.GetString("CTRLGLMFASTATUS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Mandatory - MFA can not be disabled.
        /// </summary>
        internal static string CTRLGLMFASTATUS1 {
            get {
                return ResourceManager.GetString("CTRLGLMFASTATUS1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Optional - MFA can be disabled in options.
        /// </summary>
        internal static string CTRLGLMFASTATUS2 {
            get {
                return ResourceManager.GetString("CTRLGLMFASTATUS2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Not required.
        /// </summary>
        internal static string CTRLGLMFASTATUS3 {
            get {
                return ResourceManager.GetString("CTRLGLMFASTATUS3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Security Policy (model).
        /// </summary>
        internal static string CTRLGLPOLICY {
            get {
                return ResourceManager.GetString("CTRLGLPOLICY", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Default User Provider.
        /// </summary>
        internal static string CTRLGLPROVIDER {
            get {
                return ResourceManager.GetString("CTRLGLPROVIDER", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Refresh rate (in milliseconds).
        /// </summary>
        internal static string CTRLGLREFRESH {
            get {
                return ResourceManager.GetString("CTRLGLREFRESH", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Replay Protection Level.
        /// </summary>
        internal static string CTRLGLREPLAY {
            get {
                return ResourceManager.GetString("CTRLGLREPLAY", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Show Authy Authenticator.
        /// </summary>
        internal static string CTRLGLSHOWAUTHY {
            get {
                return ResourceManager.GetString("CTRLGLSHOWAUTHY", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Show Google Authenticator.
        /// </summary>
        internal static string CTRLGLSHOWGOOGLE {
            get {
                return ResourceManager.GetString("CTRLGLSHOWGOOGLE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Show Microsoft Authenticator.
        /// </summary>
        internal static string CTRLGLSHOWMICROSOFT {
            get {
                return ResourceManager.GetString("CTRLGLSHOWMICROSOFT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à rfc6238 support - Your authenticator app must support it (Yubico, Authy) .
        /// </summary>
        internal static string CTRLGLTOTPWARN {
            get {
                return ResourceManager.GetString("CTRLGLTOTPWARN", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Use authentication applications (Google Authenticator, Microsoft Authenticator).
        /// </summary>
        internal static string CTRLGLUSEAPPS {
            get {
                return ResourceManager.GetString("CTRLGLUSEAPPS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Use email notifications.
        /// </summary>
        internal static string CTRLGLUSEMAILS {
            get {
                return ResourceManager.GetString("CTRLGLUSEMAILS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Use SMS notifications.
        /// </summary>
        internal static string CTRLGLUSESMS {
            get {
                return ResourceManager.GetString("CTRLGLUSESMS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Use browser languages.
        /// </summary>
        internal static string CTRLGLUSEUSERLANGS {
            get {
                return ResourceManager.GetString("CTRLGLUSEUSERLANGS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Invalid value, must be between {0} and {1}..
        /// </summary>
        internal static string CTRLINVALIDVALUE {
            get {
                return ResourceManager.GetString("CTRLINVALIDVALUE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Keys Repository (full class).
        /// </summary>
        internal static string CTRLKEYSREPOASSEMBLY {
            get {
                return ResourceManager.GetString("CTRLKEYSREPOASSEMBLY", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à (*) Supports multi-valued string properties.
        /// </summary>
        internal static string CTRLMULTVALUED {
            get {
                return ResourceManager.GetString("CTRLMULTVALUED", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Operation aborted ! your must start the local ADFS service !.
        /// </summary>
        internal static string CTRLMUSTACTIVATESVC {
            get {
                return ResourceManager.GetString("CTRLMUSTACTIVATESVC", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à (**) Require multi-valued string property.
        /// </summary>
        internal static string CTRLMUSTMULTVALUED {
            get {
                return ResourceManager.GetString("CTRLMUSTMULTVALUED", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Null or empty values are not allowed..
        /// </summary>
        internal static string CTRLNULLOREMPTYERROR {
            get {
                return ResourceManager.GetString("CTRLNULLOREMPTYERROR", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Active.
        /// </summary>
        internal static string CTRLPROVACTIVE {
            get {
                return ResourceManager.GetString("CTRLPROVACTIVE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Pin code required.
        /// </summary>
        internal static string CTRLPROVPIN {
            get {
                return ResourceManager.GetString("CTRLPROVPIN", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Enable PIN for specific authenticator when user presence not detected.
        /// </summary>
        internal static string CTRLPROVPINREQUIRED {
            get {
                return ResourceManager.GetString("CTRLPROVPINREQUIRED", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Required.
        /// </summary>
        internal static string CTRLPROVREQUIRED {
            get {
                return ResourceManager.GetString("CTRLPROVREQUIRED", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Enrollement Wizard.
        /// </summary>
        internal static string CTRLPROVWIZARD {
            get {
                return ResourceManager.GetString("CTRLPROVWIZARD", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Force wizard if not completed.
        /// </summary>
        internal static string CTRLPROVWIZARDSTRICT {
            get {
                return ResourceManager.GetString("CTRLPROVWIZARDSTRICT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Save.
        /// </summary>
        internal static string CTRLSAVE {
            get {
                return ResourceManager.GetString("CTRLSAVE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Implementation (full class).
        /// </summary>
        internal static string CTRLSECASSEMBLY {
            get {
                return ResourceManager.GetString("CTRLSECASSEMBLY", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Period of validity.
        /// </summary>
        internal static string CTRLSECCERTIFDURATION {
            get {
                return ResourceManager.GetString("CTRLSECCERTIFDURATION", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Certificates.
        /// </summary>
        internal static string CTRLSECCERTIFICATES {
            get {
                return ResourceManager.GetString("CTRLSECCERTIFICATES", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Use one certificate per user.
        /// </summary>
        internal static string CTRLSECCERTPERUSER {
            get {
                return ResourceManager.GetString("CTRLSECCERTPERUSER", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Certificate not found !.
        /// </summary>
        internal static string CTRLSECINVALIDCERT {
            get {
                return ResourceManager.GetString("CTRLSECINVALIDCERT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Invalid Extension ! cannot be loaded !.
        /// </summary>
        internal static string CTRLSECINVALIDEXTERROR {
            get {
                return ResourceManager.GetString("CTRLSECINVALIDEXTERROR", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Generated key length.
        /// </summary>
        internal static string CTRLSECKEYGEN {
            get {
                return ResourceManager.GetString("CTRLSECKEYGEN", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Maximum key length.
        /// </summary>
        internal static string CTRLSECKEYLENGTH {
            get {
                return ResourceManager.GetString("CTRLSECKEYLENGTH", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Security Key Mode.
        /// </summary>
        internal static string CTRLSECKEYMODE {
            get {
                return ResourceManager.GetString("CTRLSECKEYMODE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Encryption Library version.
        /// </summary>
        internal static string CTRLSECLIBLABEL {
            get {
                return ResourceManager.GetString("CTRLSECLIBLABEL", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à New certificate.
        /// </summary>
        internal static string CTRLSECNEWCERT {
            get {
                return ResourceManager.GetString("CTRLSECNEWCERT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Certificate created successfully ! You must deploy new certificate {0} on all others ADFS servers.
        /// </summary>
        internal static string CTRLSECNEWCERTCREATED {
            get {
                return ResourceManager.GetString("CTRLSECNEWCERTCREATED", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Create SQL crypted database.
        /// </summary>
        internal static string CTRLSECNEWCRYPTEDDATABASE {
            get {
                return ResourceManager.GetString("CTRLSECNEWCRYPTEDDATABASE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Create SQL Database.
        /// </summary>
        internal static string CTRLSECNEWDATABASE {
            get {
                return ResourceManager.GetString("CTRLSECNEWDATABASE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Parameters.
        /// </summary>
        internal static string CTRLSECPARAMS {
            get {
                return ResourceManager.GetString("CTRLSECPARAMS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Confirm the creation of a new certificate for MFA ? \rCaution: All existing keys will be invalidated !.
        /// </summary>
        internal static string CTRLSECRSAGENERATE {
            get {
                return ResourceManager.GetString("CTRLSECRSAGENERATE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Certificate thumbprint.
        /// </summary>
        internal static string CTRLSECTHUMPRINT {
            get {
                return ResourceManager.GetString("CTRLSECTHUMPRINT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Warning ! Changing these values will invalidate all current keys.
        /// </summary>
        internal static string CTRLSECWARNING {
            get {
                return ResourceManager.GetString("CTRLSECWARNING", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Registration wizard options.
        /// </summary>
        internal static string CTRLSECWIZARD {
            get {
                return ResourceManager.GetString("CTRLSECWIZARD", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Create a new SQL database.
        /// </summary>
        internal static string CTRLSECWIZTITLE {
            get {
                return ResourceManager.GetString("CTRLSECWIZTITLE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Application Name.
        /// </summary>
        internal static string CTRLSECWSMANAPPNAME {
            get {
                return ResourceManager.GetString("CTRLSECWSMANAPPNAME", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Port.
        /// </summary>
        internal static string CTRLSECWSMANPORT {
            get {
                return ResourceManager.GetString("CTRLSECWSMANPORT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Shell Uri.
        /// </summary>
        internal static string CTRLSECWSMANSHELLURI {
            get {
                return ResourceManager.GetString("CTRLSECWSMANSHELLURI", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Timeout.
        /// </summary>
        internal static string CTRLSECWSMANTIMEOUT {
            get {
                return ResourceManager.GetString("CTRLSECWSMANTIMEOUT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Passphrase.
        /// </summary>
        internal static string CTRLSECXORLABEL {
            get {
                return ResourceManager.GetString("CTRLSECXORLABEL", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Implementation (full class).
        /// </summary>
        internal static string CTRLSMSASSEMBLY {
            get {
                return ResourceManager.GetString("CTRLSMSASSEMBLY", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Asynchronous calls.
        /// </summary>
        internal static string CTRLSMSASYNCCALL {
            get {
                return ResourceManager.GetString("CTRLSMSASYNCCALL", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Company Name.
        /// </summary>
        internal static string CTRLSMSCOMPANY {
            get {
                return ResourceManager.GetString("CTRLSMSCOMPANY", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Invalid Extension ! cannot be loaded !.
        /// </summary>
        internal static string CTRLSMSIVALIDEXTERROR {
            get {
                return ResourceManager.GetString("CTRLSMSIVALIDEXTERROR", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Parameters.
        /// </summary>
        internal static string CTRLSMSPARAMS {
            get {
                return ResourceManager.GetString("CTRLSMSPARAMS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à SHA1 salt.
        /// </summary>
        internal static string CTRLSMSSHA1 {
            get {
                return ResourceManager.GetString("CTRLSMSSHA1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Time Out.
        /// </summary>
        internal static string CTRLSMSTIMEOUT {
            get {
                return ResourceManager.GetString("CTRLSMSTIMEOUT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Connection account.
        /// </summary>
        internal static string CTRLSMTPACCOUNT {
            get {
                return ResourceManager.GetString("CTRLSMTPACCOUNT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Anonymous.
        /// </summary>
        internal static string CTRLSMTPANONYMOUS {
            get {
                return ResourceManager.GetString("CTRLSMTPANONYMOUS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Company Name.
        /// </summary>
        internal static string CTRLSMTPCOMPANY {
            get {
                return ResourceManager.GetString("CTRLSMTPCOMPANY", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Delivery Notifications (errors).
        /// </summary>
        internal static string CTRLSMTPDELIVERYNOTIFICATIONS {
            get {
                return ResourceManager.GetString("CTRLSMTPDELIVERYNOTIFICATIONS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Administrative contact (from).
        /// </summary>
        internal static string CTRLSMTPFROM {
            get {
                return ResourceManager.GetString("CTRLSMTPFROM", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Identification.
        /// </summary>
        internal static string CTRLSMTPIDENTIFICATION {
            get {
                return ResourceManager.GetString("CTRLSMTPIDENTIFICATION", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Invalid email format !.
        /// </summary>
        internal static string CTRLSMTPMAILERROR {
            get {
                return ResourceManager.GetString("CTRLSMTPMAILERROR", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Test message sent to.
        /// </summary>
        internal static string CTRLSMTPMESSAGEOK {
            get {
                return ResourceManager.GetString("CTRLSMTPMESSAGEOK", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Password.
        /// </summary>
        internal static string CTRLSMTPPASSWORD {
            get {
                return ResourceManager.GetString("CTRLSMTPPASSWORD", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Port.
        /// </summary>
        internal static string CTRLSMTPPORT {
            get {
                return ResourceManager.GetString("CTRLSMTPPORT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Invalid port number !.
        /// </summary>
        internal static string CTRLSMTPPORTERROR {
            get {
                return ResourceManager.GetString("CTRLSMTPPORTERROR", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Mail server.
        /// </summary>
        internal static string CTRLSMTPSERVER {
            get {
                return ResourceManager.GetString("CTRLSMTPSERVER", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Server Address.
        /// </summary>
        internal static string CTRLSMTPSERVERADDRESS {
            get {
                return ResourceManager.GetString("CTRLSMTPSERVERADDRESS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Test.
        /// </summary>
        internal static string CTRLSMTPTEST {
            get {
                return ResourceManager.GetString("CTRLSMTPTEST", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Unable to connect to MFA SQL Database !.
        /// </summary>
        internal static string CTRLSQLCONNECTERROR {
            get {
                return ResourceManager.GetString("CTRLSQLCONNECTERROR", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Connection on MFA SQL Database operational !.
        /// </summary>
        internal static string CTRLSQLCONNECTOK {
            get {
                return ResourceManager.GetString("CTRLSQLCONNECTOK", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Connection string.
        /// </summary>
        internal static string CTRLSQLCONNECTSTR {
            get {
                return ResourceManager.GetString("CTRLSQLCONNECTSTR", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Invalid SQL Connection String !.
        /// </summary>
        internal static string CTRLSQLCONNECTSTRERROR {
            get {
                return ResourceManager.GetString("CTRLSQLCONNECTSTRERROR", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Create MFA Encrypted Database.
        /// </summary>
        internal static string CTRLSQLCREATECRYPTEDDB {
            get {
                return ResourceManager.GetString("CTRLSQLCREATECRYPTEDDB", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Create MFA Database.
        /// </summary>
        internal static string CTRLSQLCREATEDB {
            get {
                return ResourceManager.GetString("CTRLSQLCREATEDB", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Use Always Encrypted feature (SQL Server 2016 +).
        /// </summary>
        internal static string CTRLSQLCRYPTUSING {
            get {
                return ResourceManager.GetString("CTRLSQLCRYPTUSING", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Name of the encryption key.
        /// </summary>
        internal static string CTRLSQLENCRYPTNAME {
            get {
                return ResourceManager.GetString("CTRLSQLENCRYPTNAME", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Invalid certificate {0}.
        /// </summary>
        internal static string CTRLSQLINVALIDCERTERROR {
            get {
                return ResourceManager.GetString("CTRLSQLINVALIDCERTERROR", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Maximum Rows .
        /// </summary>
        internal static string CTRLSQLMAXROWS {
            get {
                return ResourceManager.GetString("CTRLSQLMAXROWS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à {0} is not valid ! must be between 1000 and 1000000.
        /// </summary>
        internal static string CTRLSQLMAXROWSERROR {
            get {
                return ResourceManager.GetString("CTRLSQLMAXROWSERROR", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à MFA Database {0} created successfully !.
        /// </summary>
        internal static string CTRLSQLNEWDBCREATED {
            get {
                return ResourceManager.GetString("CTRLSQLNEWDBCREATED", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à MFA Database {0} created successfully ! You must deploy new certificate {1} on all others ADFS servers.
        /// </summary>
        internal static string CTRLSQLNEWDBCREATED2 {
            get {
                return ResourceManager.GetString("CTRLSQLNEWDBCREATED2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Reuse Certificate.
        /// </summary>
        internal static string CTRLSQLREUSECERT {
            get {
                return ResourceManager.GetString("CTRLSQLREUSECERT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Test.
        /// </summary>
        internal static string CTRLSQLTEST {
            get {
                return ResourceManager.GetString("CTRLSQLTEST", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Certificate thumprint.
        /// </summary>
        internal static string CTRLSQLTHUMBPRINT {
            get {
                return ResourceManager.GetString("CTRLSQLTHUMBPRINT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Use SQL Server configuration.
        /// </summary>
        internal static string CTRLSQLUSING {
            get {
                return ResourceManager.GetString("CTRLSQLUSING", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Use Active Directory.
        /// </summary>
        internal static string CTRLSTUSEADDS {
            get {
                return ResourceManager.GetString("CTRLSTUSEADDS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Use Custom Storage.
        /// </summary>
        internal static string CTRLSTUSECUSTOM {
            get {
                return ResourceManager.GetString("CTRLSTUSECUSTOM", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Use SQL Server.
        /// </summary>
        internal static string CTRLSTUSESQL {
            get {
                return ResourceManager.GetString("CTRLSTUSESQL", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Authenticator Attachement.
        /// </summary>
        internal static string CTRLWEBAUTHNATTACHEMENT {
            get {
                return ResourceManager.GetString("CTRLWEBAUTHNATTACHEMENT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Fast Login.
        /// </summary>
        internal static string CTRLWEBAUTHNAUTOLOGIN {
            get {
                return ResourceManager.GetString("CTRLWEBAUTHNAUTOLOGIN", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Challenge Size.
        /// </summary>
        internal static string CTRLWEBAUTHNCHALLENGE {
            get {
                return ResourceManager.GetString("CTRLWEBAUTHNCHALLENGE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Attestation Conveyance Preference.
        /// </summary>
        internal static string CTRLWEBAUTHNCONVEYANCE {
            get {
                return ResourceManager.GetString("CTRLWEBAUTHNCONVEYANCE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Timestamp Drift Tolerance.
        /// </summary>
        internal static string CTRLWEBAUTHNDRIFTTOLERANCE {
            get {
                return ResourceManager.GetString("CTRLWEBAUTHNDRIFTTOLERANCE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Extensions (authnSe).
        /// </summary>
        internal static string CTRLWEBAUTHNEXTENSIONS {
            get {
                return ResourceManager.GetString("CTRLWEBAUTHNEXTENSIONS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Require resident Key.
        /// </summary>
        internal static string CTRLWEBAUTHNRESIDENTKEY {
            get {
                return ResourceManager.GetString("CTRLWEBAUTHNRESIDENTKEY", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Require a valid attestation root certificate.
        /// </summary>
        internal static string CTRLWEBAUTHNROOTATTESTATION {
            get {
                return ResourceManager.GetString("CTRLWEBAUTHNROOTATTESTATION", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Server Domain.
        /// </summary>
        internal static string CTRLWEBAUTHNSERVERDOMAIN {
            get {
                return ResourceManager.GetString("CTRLWEBAUTHNSERVERDOMAIN", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Server Name.
        /// </summary>
        internal static string CTRLWEBAUTHNSERVERNAME {
            get {
                return ResourceManager.GetString("CTRLWEBAUTHNSERVERNAME", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Server Url.
        /// </summary>
        internal static string CTRLWEBAUTHNSERVERURL {
            get {
                return ResourceManager.GetString("CTRLWEBAUTHNSERVERURL", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Show sensitive logs.
        /// </summary>
        internal static string CTRLWEBAUTHNSHOWPII {
            get {
                return ResourceManager.GetString("CTRLWEBAUTHNSHOWPII", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Timeout (ms).
        /// </summary>
        internal static string CTRLWEBAUTHNTIMEOUT {
            get {
                return ResourceManager.GetString("CTRLWEBAUTHNTIMEOUT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à User verification index (uvi).
        /// </summary>
        internal static string CTRLWEBAUTHNUSERINDEX {
            get {
                return ResourceManager.GetString("CTRLWEBAUTHNUSERINDEX", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à User Location.
        /// </summary>
        internal static string CTRLWEBAUTHNUSERLOCATION {
            get {
                return ResourceManager.GetString("CTRLWEBAUTHNUSERLOCATION", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à User verification method (uvm).
        /// </summary>
        internal static string CTRLWEBAUTHNUSERMETHOD {
            get {
                return ResourceManager.GetString("CTRLWEBAUTHNUSERMETHOD", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à User Attestation Verification Requirement.
        /// </summary>
        internal static string CTRLWEBAUTHNUSERVERFICATION {
            get {
                return ResourceManager.GetString("CTRLWEBAUTHNUSERVERFICATION", resourceCulture);
            }
        }
    }
}
