//------------------------------------------------------------------------------
// <auto-generated>
//     Ce code a été généré par un outil.
//     Version du runtime :4.0.30319.42000
//
//     Les modifications apportées à ce fichier peuvent provoquer un comportement incorrect et seront perdues si
//     le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Neos.IdentityServer.MultiFactor.Common.Resources {
    using System;
    
    
    /// <summary>
    ///   Une classe de ressource fortement typée destinée, entre autres, à la consultation des chaînes localisées.
    /// </summary>
    // Cette classe a été générée automatiquement par la classe StronglyTypedResourceBuilder
    // à l'aide d'un outil, tel que ResGen ou Visual Studio.
    // Pour ajouter ou supprimer un membre, modifiez votre fichier .ResX, puis réexécutez ResGen
    // avec l'option /str ou régénérez votre projet VS.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "15.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class CSMail {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal CSMail() {
        }
        
        /// <summary>
        ///   Retourne l'instance ResourceManager mise en cache utilisée par cette classe.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Neos.IdentityServer.MultiFactor.Common.Resources.CSMail", typeof(CSMail).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Remplace la propriété CurrentUICulture du thread actuel pour toutes
        ///   les recherches de ressources à l'aide de cette classe de ressource fortement typée.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à &lt;!DOCTYPE HTML PUBLIC &quot;-//W3C//DTD HTML 4.01 Transitional//EN&quot; &quot;http://www.w3.org/TR/html4/loose.dtd&quot;&gt; 
        ///&lt;html&gt; 
        ///    &lt;head&gt; 
        ///        &lt;title&gt;&lt;/title&gt; 
        ///        &lt;base target=&quot;_blank&quot;&gt; 
        ///    &lt;/head&gt; 
        ///    &lt;body&gt; 
        ///        &lt;table dir=&quot;ltr&quot;&gt;
        ///            &lt;tr&gt;
        ///                &lt;td id=&quot;i1&quot; style=&quot;padding:0;font-family:&apos;Segoe UI Semibold&apos;, &apos;Segoe UI Bold&apos;, &apos;Segoe UI&apos;, &apos;Helvetica Neue Medium&apos;, Arial, sans-serif;font-size:17px;color:#707070;&quot;&gt;{0} Account&lt;/td&gt;
        ///            &lt;/tr&gt; 
        ///            &lt;tr&gt;
        ///                &lt; [le reste de la chaîne a été tronqué]&quot;;.
        /// </summary>
        public static string MailAdminContent {
            get {
                return ResourceManager.GetString("MailAdminContent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Administrative request for {0} registration.
        /// </summary>
        public static string MailAdminTitle {
            get {
                return ResourceManager.GetString("MailAdminTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à &lt;!DOCTYPE HTML PUBLIC &quot;-//W3C//DTD HTML 4.01 Transitional//EN&quot; &quot;http://www.w3.org/TR/html4/loose.dtd&quot;&gt; 
        ///&lt;html&gt; 
        ///    &lt;head&gt; 
        ///        &lt;title&gt;&lt;/title&gt; 
        ///        &lt;base target=&quot;_blank&quot;&gt; 
        ///    &lt;/head&gt; 
        ///    &lt;body&gt; 
        ///        &lt;table dir=&quot;ltr&quot;&gt;
        ///            &lt;tr&gt;
        ///                &lt;td id=&quot;i1&quot; style=&quot;padding:0;font-family:&apos;Segoe UI Semibold&apos;, &apos;Segoe UI Bold&apos;, &apos;Segoe UI&apos;, &apos;Helvetica Neue Medium&apos;, Arial, sans-serif;font-size:17px;color:#707070;&quot;&gt;{0} Account&lt;/td&gt;
        ///            &lt;/tr&gt; 
        ///            &lt;tr&gt;
        ///                &lt; [le reste de la chaîne a été tronqué]&quot;;.
        /// </summary>
        public static string MailKeyContent {
            get {
                return ResourceManager.GetString("MailKeyContent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Security information.
        /// </summary>
        public static string MailKeyTitle {
            get {
                return ResourceManager.GetString("MailKeyTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à &lt;!DOCTYPE HTML PUBLIC &quot;-//W3C//DTD HTML 4.01 Transitional//EN&quot; &quot;http://www.w3.org/TR/html4/loose.dtd&quot;&gt;
        ///&lt;html&gt;
        ///&lt;head&gt;
        ///    &lt;title&gt;&lt;/title&gt;
        ///    &lt;base target=&quot;_blank&quot;&gt;
        ///&lt;/head&gt;
        ///&lt;body&gt;
        ///    &lt;table dir=&quot;ltr&quot;&gt;
        ///        &lt;tr&gt;
        ///            &lt;td id=&quot;i2&quot; style=&quot;padding:0;font-family:&apos;Segoe UI Light&apos;, &apos;Segoe UI&apos;, &apos;Helvetica Neue Medium&apos;, Arial, sans-serif;font-size:41px;color:#2672ec;&quot;&gt;Your security information has been changed&lt;/td&gt;
        ///        &lt;/tr&gt;
        ///        &lt;tr&gt;
        ///            &lt;td id=&quot;i3&quot; style=&quot;padding:0;padding-top:2 [le reste de la chaîne a été tronqué]&quot;;.
        /// </summary>
        public static string MailNotifications {
            get {
                return ResourceManager.GetString("MailNotifications", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Security alert about your {0} account.
        /// </summary>
        public static string MailNotificationsTitle {
            get {
                return ResourceManager.GetString("MailNotificationsTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à &lt;!DOCTYPE HTML PUBLIC &quot;-//W3C//DTD HTML 4.01 Transitional//EN&quot; &quot;http://www.w3.org/TR/html4/loose.dtd&quot;&gt; 
        ///&lt;html&gt; 
        /// &lt;head&gt; 
        ///  &lt;title&gt;&lt;/title&gt; 
        ///  &lt;base target=&quot;_blank&quot;&gt; 
        /// &lt;/head&gt; 
        /// &lt;body&gt; 
        ///  &lt;table dir=&quot;ltr&quot;&gt; 
        ///   &lt;tr&gt; 
        ///    &lt;td id=&quot;i1&quot; style=&quot;padding:0;font-family:&apos;Segoe UI Semibold&apos;, &apos;Segoe UI Bold&apos;, &apos;Segoe UI&apos;, &apos;Helvetica Neue Medium&apos;, Arial, sans-serif;font-size:17px;color:#707070;&quot;&gt;{0} account&lt;/td&gt; 
        ///   &lt;/tr&gt; 
        ///   &lt;tr&gt; 
        ///    &lt;td id=&quot;i2&quot; style=&quot;padding:0;font-family:&apos;Segoe UI Light&apos;, &apos;Segoe UI&apos;, &apos;Hel [le reste de la chaîne a été tronqué]&quot;;.
        /// </summary>
        public static string MailOTPContent {
            get {
                return ResourceManager.GetString("MailOTPContent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Security Code.
        /// </summary>
        public static string MailOTPTitle {
            get {
                return ResourceManager.GetString("MailOTPTitle", resourceCulture);
            }
        }
    }
}
