//------------------------------------------------------------------------------
// <auto-generated>
//     Ce code a été généré par un outil.
//     Version du runtime :4.0.30319.42000
//
//     Les modifications apportées à ce fichier peuvent provoquer un comportement incorrect et seront perdues si
//     le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Neos.IdentityServer.MultiFactor.Cmdlets.Ressources {
    using System;
    
    
    /// <summary>
    ///   Une classe de ressource fortement typée destinée, entre autres, à la consultation des chaînes localisées.
    /// </summary>
    // Cette classe a été générée automatiquement par la classe StronglyTypedResourceBuilder
    // à l'aide d'un outil, tel que ResGen ou Visual Studio.
    // Pour ajouter ou supprimer un membre, modifiez votre fichier .ResX, puis réexécutez ResGen
    // avec l'option /str ou régénérez votre projet VS.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "15.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class infos_strings {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal infos_strings() {
        }
        
        /// <summary>
        ///   Retourne l'instance ResourceManager mise en cache utilisée par cette classe.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Neos.IdentityServer.MultiFactor.Cmdlets.Ressources.infos_strings", typeof(infos_strings).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Remplace la propriété CurrentUICulture du thread actuel pour toutes
        ///   les recherches de ressources à l'aide de cette classe de ressource fortement typée.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à All RSA keys will be invalidated ! Continue (Y/N).
        /// </summary>
        internal static string InfoAllKeyWillbeReset {
            get {
                return ResourceManager.GetString("InfoAllKeyWillbeReset", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à ADFS Certificate correctly created ! You must deploy this certificate on all ADFS servers..
        /// </summary>
        internal static string InfosADFSCertificateChanged {
            get {
                return ResourceManager.GetString("InfosADFSCertificateChanged", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à All Farm Services Restarted !.
        /// </summary>
        internal static string InfosAllServicesRestarted {
            get {
                return ResourceManager.GetString("InfosAllServicesRestarted", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Access Control List updated for all MFA certificates !.
        /// </summary>
        internal static string InfosCertsACLUpdated {
            get {
                return ResourceManager.GetString("InfosCertsACLUpdated", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à MFA Configuration updated !.
        /// </summary>
        internal static string InfosConfigUpdated {
            get {
                return ResourceManager.GetString("InfosConfigUpdated", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Database {0} created !.
        /// </summary>
        internal static string InfosDatabaseCreated {
            get {
                return ResourceManager.GetString("InfosDatabaseCreated", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Database {0} upgraded !.
        /// </summary>
        internal static string InfosDatabaseUpgraded {
            get {
                return ResourceManager.GetString("InfosDatabaseUpgraded", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Number of deleted orphaned private keys.
        /// </summary>
        internal static string InfosOrphanedDeleted {
            get {
                return ResourceManager.GetString("InfosOrphanedDeleted", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Records count : {0}.
        /// </summary>
        internal static string InfosRecordsCount {
            get {
                return ResourceManager.GetString("InfosRecordsCount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à MFA certificate {0} correctly updated ! You must deploy this certificate on all others ADFS servers..
        /// </summary>
        internal static string InfosRSACertificateChanged {
            get {
                return ResourceManager.GetString("InfosRSACertificateChanged", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Services on server {0} Restarted !.
        /// </summary>
        internal static string InfosServerServicesRestarted {
            get {
                return ResourceManager.GetString("InfosServerServicesRestarted", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à SQL certificate {0} correctly updated ! You must deploy this certificate on all others ADFS servers..
        /// </summary>
        internal static string InfosSQLCertificateChanged {
            get {
                return ResourceManager.GetString("InfosSQLCertificateChanged", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à MFA is already initialized ! you must run &quot;UnRegister-MFASystem&quot; PowerShell Cmdlet if you want to reinitialize ALL the MFA configuration.
        /// </summary>
        internal static string InfosSystemAlreadyInitialized {
            get {
                return ResourceManager.GetString("InfosSystemAlreadyInitialized", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à MFA Configuration correctly exported to file {0} !.
        /// </summary>
        internal static string InfosSystemExported {
            get {
                return ResourceManager.GetString("InfosSystemExported", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à MFA Configuration correctly imported from file {0} !.
        /// </summary>
        internal static string InfosSystemImported {
            get {
                return ResourceManager.GetString("InfosSystemImported", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à MFA Configuration Import with errors !.
        /// </summary>
        internal static string InfosSystemInInvalidState {
            get {
                return ResourceManager.GetString("InfosSystemInInvalidState", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à MFA System correctly registered ! .
        /// </summary>
        internal static string InfosSystemRegistered {
            get {
                return ResourceManager.GetString("InfosSystemRegistered", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à MFA System correctly unconfigured !.
        /// </summary>
        internal static string InfosSystemUnRegistered {
            get {
                return ResourceManager.GetString("InfosSystemUnRegistered", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à MFA Threat System Data was not correctly updated !.
        /// </summary>
        internal static string InfosThreatDataNotUpdated {
            get {
                return ResourceManager.GetString("InfosThreatDataNotUpdated", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à MFA Threat System Data correctly updated !.
        /// </summary>
        internal static string InfosThreatDataUpdated {
            get {
                return ResourceManager.GetString("InfosThreatDataUpdated", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à MFA Threat System was not correctly registered ! .
        /// </summary>
        internal static string InfosThreatSystemNotRegistered {
            get {
                return ResourceManager.GetString("InfosThreatSystemNotRegistered", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à MFA Threat System was not correctly unconfigured !.
        /// </summary>
        internal static string InfosThreatSystemNotUnRegistered {
            get {
                return ResourceManager.GetString("InfosThreatSystemNotUnRegistered", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à MFA Threat System correctly registered ! .
        /// </summary>
        internal static string InfosThreatSystemRegistered {
            get {
                return ResourceManager.GetString("InfosThreatSystemRegistered", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à MFA Threat System correctly unconfigured !.
        /// </summary>
        internal static string InfosThreatSystemUnRegistered {
            get {
                return ResourceManager.GetString("InfosThreatSystemUnRegistered", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à User {0} added !.
        /// </summary>
        internal static string InfosUserAdded {
            get {
                return ResourceManager.GetString("InfosUserAdded", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à User {0} deleted !.
        /// </summary>
        internal static string InfosUserDeleted {
            get {
                return ResourceManager.GetString("InfosUserDeleted", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à User {0} has a new Enryption key !.
        /// </summary>
        internal static string InfosUserHasNewKey {
            get {
                return ResourceManager.GetString("InfosUserHasNewKey", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à User {0} updated !.
        /// </summary>
        internal static string InfosUserUpdated {
            get {
                return ResourceManager.GetString("InfosUserUpdated", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à CAUTION ! your theme must be fully compatible (js, css, etc...) with the UI you choose : {0}.
        /// </summary>
        internal static string InfosWarningAboutTheme {
            get {
                return ResourceManager.GetString("InfosWarningAboutTheme", resourceCulture);
            }
        }
    }
}
