//------------------------------------------------------------------------------
// <auto-generated>
//     Ce code a été généré par un outil.
//     Version du runtime :4.0.30319.42000
//
//     Les modifications apportées à ce fichier peuvent provoquer un comportement incorrect et seront perdues si
//     le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Neos.IdentityServer.Console.Resources {
    using System;
    
    
    /// <summary>
    ///   Une classe de ressource fortement typée destinée, entre autres, à la consultation des chaînes localisées.
    /// </summary>
    // Cette classe a été générée automatiquement par la classe StronglyTypedResourceBuilder
    // à l'aide d'un outil, tel que ResGen ou Visual Studio.
    // Pour ajouter ou supprimer un membre, modifiez votre fichier .ResX, puis réexécutez ResGen
    // avec l'option /str ou régénérez votre projet VS.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "15.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Neos_IdentityServer_Console_DataContracts {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Neos_IdentityServer_Console_DataContracts() {
        }
        
        /// <summary>
        ///   Retourne l'instance ResourceManager mise en cache utilisée par cette classe.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Neos.IdentityServer.Console.Resources.Neos.IdentityServer.Console.DataContracts", typeof(Neos_IdentityServer_Console_DataContracts).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Remplace la propriété CurrentUICulture du thread actuel pour toutes
        ///   les recherches de ressources à l'aide de cette classe de ressource fortement typée.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à E-mail address.
        /// </summary>
        internal static string MMCFILTEREMAIL {
            get {
                return ResourceManager.GetString("MMCFILTEREMAIL", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Phone Number.
        /// </summary>
        internal static string MMCFILTERPHONE {
            get {
                return ResourceManager.GetString("MMCFILTERPHONE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à User account.
        /// </summary>
        internal static string MMCFILTERUSERNAME {
            get {
                return ResourceManager.GetString("MMCFILTERUSERNAME", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Use an application on mobile or pc.
        /// </summary>
        internal static string MMCMETHAPP {
            get {
                return ResourceManager.GetString("MMCMETHAPP", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Microsoft Azure.
        /// </summary>
        internal static string MMCMETHAZURE {
            get {
                return ResourceManager.GetString("MMCMETHAZURE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Biometric Device.
        /// </summary>
        internal static string MMCMETHBIO {
            get {
                return ResourceManager.GetString("MMCMETHBIO", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Choose the best method.
        /// </summary>
        internal static string MMCMETHCHOOSE {
            get {
                return ResourceManager.GetString("MMCMETHCHOOSE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Receive an email.
        /// </summary>
        internal static string MMCMETHEMAIL {
            get {
                return ResourceManager.GetString("MMCMETHEMAIL", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à (none).
        /// </summary>
        internal static string MMCMETHNONE {
            get {
                return ResourceManager.GetString("MMCMETHNONE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Receive a message on my phone.
        /// </summary>
        internal static string MMCMETHPHONE {
            get {
                return ResourceManager.GetString("MMCMETHPHONE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Contains.
        /// </summary>
        internal static string MMCOPCONTAINS {
            get {
                return ResourceManager.GetString("MMCOPCONTAINS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Finish by.
        /// </summary>
        internal static string MMCOPENDSWITH {
            get {
                return ResourceManager.GetString("MMCOPENDSWITH", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Is equal to.
        /// </summary>
        internal static string MMCOPEQUAL {
            get {
                return ResourceManager.GetString("MMCOPEQUAL", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Does not contain.
        /// </summary>
        internal static string MMCOPNOTCONTAINS {
            get {
                return ResourceManager.GetString("MMCOPNOTCONTAINS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Is not equal to.
        /// </summary>
        internal static string MMCOPNOTEQUAL {
            get {
                return ResourceManager.GetString("MMCOPNOTEQUAL", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Starts with.
        /// </summary>
        internal static string MMCOPSTARTWITH {
            get {
                return ResourceManager.GetString("MMCOPSTARTWITH", resourceCulture);
            }
        }
    }
}
